### ISSUE TITLE
Language selection creates link to Language

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#113]
**Describe the bug**
When select a Language, I guess the Language setting creates a page for that Language. It causes a link in the Show Info for Language: (insert language here) for the Language and the page 404's because there is no page created for a language.

**To Reproduce**
1. Go to Show 4
2. View the Language set for the Show
3. The language is hyperlinked, click the link
4. Return 404 page not found

**Expected behavior**
The language should not be linked to any page.

Related to #112

**Comment by majick777** [comment]
The Language labels have been fixed as in #112. The links don't 404 for me now, but they are meant to be there as they are actually to the language terms archive page for that term - listing all posts with that term. Similar to how any taxonomy works in WordPress, such as the same for the Genre links. This ia a feature so that visitors can easlly find other Shows with the same Genre / Language.

**Comment by tonyzeoli** [comment]
Okay, got it. Didn't know that was the intended functionality. Thanks!
