### ISSUE TITLE
Show title needs top padding, is too close to Featured Image

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#120]
**Describe the bug**
The Show Title is too close to the bottom of the Featured Image. Needs some padding for the row to give it whitespace at the bottom of the Featured Image

**To Reproduce**
1. Go to Show Page
2. View Title
3. See not enough whitespace between Show Title and Featured Image

**Expected behavior**
Should have correct padding between show Featured Image and Show Title

**Screenshots**

<img width="680" alt="Screen Shot 2020-01-06 at 8 19 18 AM" src="https://user-images.githubusercontent.com/4053819/71820619-a6fe5900-305d-11ea-9544-966a1871ffad.png">

**Comment by majick777** [comment]
This is a theme style issue and outside of the content area where the Show template displays. We can't introduce styles into the plugin that will override the default title padding because 1. we don't know have any way of knowing the page element selectors and 2. a plugin shouldn't override theme styles anyway. 

The best we can do in this case is to fix this style issue for display on the demo site. Something like
`.single-show .entry-title {padding-top: 20px;}` should be sufficient.

**Comment by tonyzeoli** [comment]
Okay - got it. Thanks!
