### ISSUE TITLE
[Show Overrides] Not overriding currently scheduled shows

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#130]
**Describe the bug**
I set an override for Saturday, 1/11 at 12:00 am and it does not override the entry on the calendar.

**To Reproduce**
1. Go Show Overrides
2. Check the only Override date and time
3. Check the Master Schedule and the Show does not Override the regularly scheduled show

**Expected behavior**

When viewing the calendar, you should see the Override entry info.

**Comment by majick777** [comment]
Was fetching override dates from the current day one week into the future... which on the surface seemed right... but really, since the schedule start day might be different to the current day, it was missing any overrides on any days in the schedule prior to the current day. 

So I set it to initially fetch override dates a week forward *and* backward. Since the overrides are already combined correctly into the schedule, this is all that was necessary to fix.

**Comment by tonyzeoli** [comment]
Confirmed fix. Thanks!
