### ISSUE TITLE
No sidebar controls on Master Schedule Page

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#137]
**Describe the bug**

Opening for discussion.

The Master Schedule page template does not include a sidebar? Is that on purpose?

Many page builders now have sidebar/no sidebar controls, so I think we can safely have a sidebar on this page and the user can control whether they want a sidebar or not.

Is there a business case not to have a sidebar on this page? I guess there probably is, whereas all show pages can have sidebars and you're going to see upcoming shows in the calendar anyway, but it was worth a mention.

You may close this if you think we should just keep the page sans sidebar.

**To Reproduce**
1. Go to Master Schedule Page
2. See there is no sidebar
3. Edit page
4. Go to Make Layout on the right column and see there is no ability to add a sidebar to this specific template, but for Show pages you can add/hide.

**Expected behavior**

**Screenshots**

<img width="298" alt="show-page-sidebar-controls" src="https://user-images.githubusercontent.com/4053819/72279427-15b25800-3604-11ea-8282-72d1f9a4972e.png">
<img width="298" alt="schedule-page-sidebar-controls" src="https://user-images.githubusercontent.com/4053819/72279428-15b25800-3604-11ea-8d3b-a4d3b4bdaa4e.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Whether a page has a sidebar is determined by the theme and the page template in the theme. 
While generally it is better practice for a theme to have this included, unfortunately this is not always done or done in a standard way. The post sidebar might be called in a page template, or a separate sidebar might be declared for pages, in which case widgets will need to be added to that for them to show on pages. (My own theme has the option for a unified or split sidebar for example, but that is a pretty rare thing to have, usually it is a case of one or the other.)

As for the Make theme on the demo site, I checked and the sidebar options seems to disappear when the Make page builder is active (the template is set to Page Builder Template instead of Default Template.) I think we should avoid using any page builder on the demo site demo pages, as it adds markup to the content that is not going to be honoured when testing other themes, which we may need to do occassionally. If we want to test page builders in the future we should create specific pages for those builders and activate those specific builders *only* on those pages.
