### ISSUE TITLE
[Show Posts] Back to Show Link on any Blog Post Attached to a Show

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#156]
**Describe the bug**

There is no way to get back to the Show page from a Blog post that is attached to a Show.

**To Reproduce**
1. Go to Show 1
2. Click on Test Blog Post
3. View Post and try to return to Show page
4. No link exists to get back to Show page

**Expected behavior**

Add a link, "Back to [Show Name]" above Post Title with return arrow < -

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
So I have added this, here are some notes...
- Similar to the show page, the top link cannot be above the post title because it is added within the content area... 
- Text for top link: Post for Show: {Linked Show Name}
- Text for bottom link: <- {All Posts for Show {Show Name}}
- Bottom link is a #hash link to jump to that Show Page section (and display that Tab if Show page sections are in tabbed view.)
- Also added same for Playlists (with adjusted anchor text)
-

**Comment by tonyzeoli** [comment]
@majick777 

Can we remove the top of the post entry and just keep the bottom.

And, after the word Show on the bottom, please add a ":"

**Comment by majick777** [comment]
Ok done... rather than removing code for top, I added a filter so if someone wants to change the display to have both or either they can. But the default is to just display the bottom link.

Also, the code for linking Playlists back to Shows I realized lives better in the Playlist content template so I moved it there rather than having it as a content filter like the Posts one.
