### ISSUE TITLE
 Illegal string offset in Table view, No Shows in Tabbed view

### ISSUE THREAD

**Issue by corbyradio** [netmix/radio-station#163]
Using the current Dev branch when we set the page to Tabbed mode we get the tabs but no schedule, when we use the default table view we get a load of errors, but the table does load, this occurs no matter what theme we use.

We are running the following;
WP: 5.3.2
PHP: 7.3
Host: Ionos (1&1 UK)

The errors we get are below;

Warning: Illegal string offset 'Monday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Monday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Tuesday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Tuesday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Wednesday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Wednesday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Thursday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Thursday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Friday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Friday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Saturday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Saturday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Sunday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Sunday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Friday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Friday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

Warning: Illegal string offset 'Friday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 335

Warning: Illegal string offset 'Friday' in /homepages/27/d604077397/htdocs/sites/corbyradio/wordpress/wp-content/plugins/radio-station/templates/master-schedule-table.php on line 336

**Comment by corbyradio** [comment]
The errors can be seen at https://corby.radio/test-page

**Comment by gusaus** [comment]
I was coming across similar issues during testing last night.

**Comment by tonyzeoli** [comment]
@majick777 Here is an indication of that this issue might be: https://www.quora.com/How-can-I-fix-this-%E2%80%9CWarning-Illegal-string-offset-style%E2%80%9D

This is most likely a PHP warning message.

This usually happens when you have a variable that holds a string, but try to access it like it was an array. Like this:

$value = "Hello, world!";
echo $value['style'];
// PHP Warning:  Illegal string offset 'style' in ... on line ...
PHP does, in fact, allow square bracket syntax for strings; it can be used to access individual characters in a string. However, the offset (i.e. the value in square brackets) has to be an integer. For example:

$value = "Hello, world!";
echo $value[7];
// w
String values (like “style”) are forbidden here. That's what the error message is saying.

You probably have a typo in your code, or have your variables mixed up; or maybe you call a function that expects an array, but is passed a string instead.

Try navigating to the line indicated by the error message, find where the "style" bit is. Double check what the whole line of code is doing, then use var_dump() or print_r() on the variable (or value) used to see what is actually in there. It should become much more clear once you see the actual values.

**Comment by majick777** [comment]
@corbyradio Thanks for the report! I have fixed the Table issue now and pushed the changes to `develop` branch with some other minor fixes. Was a singular-plural typo in the new day-to-date conversion recently added (for more reliable shift time checking.) Was fine everywhere else.

I will close this issue, but if you could open another one for the Tabbed view with more details of what is going on there it would be appreciated, so we can attempt to reproduce. I am not seeing any current issues with it myself, either via the shortcode or setting it as the View for the Automatic Page:  https://radiostationdemo.com/automatic-pages/schedule-page/
