### ISSUE TITLE
[Master Schedule Views] Add Show Description Shortcode Attribute

### ISSUE THREAD

**Issue by corbyradio** [netmix/radio-station#165]
Is it possible with the tabbed view to include a short description of the show, maybe through a custom field, it would be good to be able to include a description so listeners can see what the show is about without having to click through to the show page.

Also, is it possible to either add the ability to remove the end time from each show or make it option? I know this can be achieved by editing the master-schedule-tabs.php however it would be nice to have this as a setting

**Comment by tonyzeoli** [comment]
@corbyradio We will consider these. I'm not sure yet that we can get to these enhancements for 2.3.0 as we've pretty much closed development and are in testing only for bugs. But, we can probably get this out in a 2.3.1 soon thereafter, barring any unforeseen issues. I'm going to split these into two feature requests with their own tickets. I'll keep this ticket for the first request and separate out the admin function to remove the end of time in a separate.

**Comment by tonyzeoli** [comment]
@corbyradio Follow here: https://github.com/netmix/radio-station/issues/166#issue-581905948 for enhancement to on/off end of time in the adm view.

**Comment by majick777** [comment]
Since we had the code handy for this from shortcodes, and it's a simple copy and paste, I've gone and included this even though it's a bit last minute. 

With the latest develop branch, you can add the attribute `show_desc="1"` to a Master Schedule shortcode (table/tabs or list view.) It is off by default.

The description comes from the show post excerpt field, which is handled by WordPress. ie. you can specify an explicit short description for the excerpt, or if one is not specified, it is generated from the full description (there are filters for the excerpt length and read more anchor if this happens.)

There are also (view-contextual) filters for these excerpt if you want to grab it from somewhere else (ie. an existing custom field.)
