### ISSUE TITLE
[Widgets] Filter default_name to allow for images

### ISSUE THREAD

**Issue by PAOK1926** [netmix/radio-station#178]
hello,

i can use the widget and set ‘default_name’ => The text you would like to display when no show is schedule for the current time.
it would be useful to be able to add an image for the “auto pilot” feature ..

regards,
George

**Comment by majick777** [comment]
I will probably just add a custom filter to this text so that it can be replaced with an image using custom code, instead of making this a full shortcode/widget option.

**Comment by majick777** [comment]
@PAOK1926 
Since this was an easy one, I have added the following filters in to the develop branch for 2.3.1:
`radio_station_no_current_show_text`
`radio_station_no_upcoming_shows_text`
`radio_station_no_current_playlist_text`
So you can use those to filter the HTML output for the corresponding shortcodes/widgets
