### ISSUE TITLE
Now Playing Info

### ISSUE THREAD

**Issue by XLRradio** [netmix/radio-station#196]
Hi All
Is it possible to include a Now Playing Widget so we could add the current now playing info from the Stream you put in so it can be visible on the website, and have options to include the size of the font etc?
tonyzeoli commented
Radio Startion already has a playlisting widget. Start your playlist under the playlist admin and assign it to a show. Add songs to playlist generator and they will appear in the widget.
We have plans to add a sidebar audio player to handle your shoutcast or icecast stream in FREE. We are just starting to look at our options and expect that will come sometime in the next 60 days.
We will offer a sticky footer player in the PRO version, which is probably 45 to 60 days out.
XLRradio commented 
@tonyzeoli No I don't mean the playlist function where you add your own playlist. I mean pulling the metadata from the stream. so whatever is playing out on a URL it comes up on the now playing widget.
XLRradio commented
@tonyzeoli bit premature weren't u? closing this subject before you get an answer????

@tonyzeoli

**Comment by tonyzeoli** [comment]
First, don’t be a snarky. You asked a question that did not provide the level of detail in your follow up. Look at your own question and tell me if you provided the same level of detail as in your follow up question. You asked the question and you left out a level of detail that you only provided in your second message. Right now, we’re all dealing with how the coronavirus is affecting each and everyone of our lives. I certainly don’t need your whining. I have enough coming from my five year old to last a lifetime.

One thing many people in software development realize is that email and chat and all the technology we have, at times, falls short in the ability to properly convey what we are thinking. People just assume you should know exactly what they are talking about when they message you and are offended when you don’t give them what they want back. But it’s on you to be clear and concise in your emails and posts in any forum, before your whine about someone closing your question when you didn’t provide the same level of detail.

Second, the only way to provide the data you’re asking for in your second question is to pull the song data from the music file or software source - i.e. the mp3 or WAV or the radio station automation software (or DJ software) that your station is using. Because that’s where the information exists. There’s also fingerprinting technology to ID music files, but now all songs are fingerprinted or fingerprinted accurately. And if you pitch up or down a song it may be out of the range of the fingerprinting technology to identify the song correctly. Or it may be the wrong version it returns.

In all cases, the data has to be correct for the user listening to view it. Many times, people play songs with incorrect meta data. The artist name might be spelled wrong, etc... And, there are probably hundreds of ways stations broadcast their streams. It’s my perception in your question that you either don’t realize this or do realize this, but haven’t provided what software you use to broadcast your stream. So I wouldn’t know how to give you what you want, because you failed to provide that level of detail.

In the future, we are planning this type of integration with open source radio station automation software but only as a paid add-on. It will not be free and can’t be free because if the level of development and support needed to a maintain multiple API connections to multiple automation packages.

So, even if you program your station with iTunes, your song data is only as good as your songs completeness to include such data. And, there’s no iTunes API that I know of at this time that can send that data to Radio Station from the desktop.

So, I am closing this based on the fact that it’s already in our cue to do something like this and it’s already part of the PRO project, so we don’t need it listed here. I could move your request to PRO, but since it already exists, I’m closing it because it’s an unnecessary duplication.

And, it won’t be in FREE anyway, unless you wanted to fund that development.

**Comment by XLRradio** [comment]
@tonyzeoli hello I am sorry if I sounded snarky. and sorry I didn't provide more information but in hindsight you could have asked for more info instead of just closing it. and OMG I would be interested in automation software

**Comment by tonyzeoli** [comment]
Thanks for your apology. 

You had a very specific request which I answered to the best of my ability given what you posted. I didn't have to ask a question, because you were asking about something we already do.

Please look into Azuracast. They have a free radio station automation software and we may be choosing that one to start with. We're already in talks with them to sync their system to Radio Station in our PRO version so that the station's using the software can A. push the track title into the player we will have in PRO, and B. create full playlists from automation without having to re-type it into WordPress.

The only caveat is these features will all be in PRO and a PRO add-on for Azuracast. We're sorry they can't be free, but this is extended functionality. You will have a player in FREE, but it will be a widget player. We could possibly integrate the Playlist feature in the player to display the track titles. But you'll have to use Radio Station's playlist generator for that - it'll be manual and not automated.
