### ISSUE TITLE
Remove above

### ISSUE THREAD

**Issue by Whaley01** [netmix/radio-station#214]
![52601E79-6DEE-4319-B702-AC6FCC435E8D](https://user-images.githubusercontent.com/65598029/82313741-b05ee100-99c0-11ea-87b4-bad9f7114316.jpeg)

Since the latest update all the above as appeared on my page all the show details above the arrow I need to remove. I can’t seem to find how to remove.  Any idea would be great

**Comment by majick777** [comment]
For information on the changes to Templates since 2.3.0, especially for the new Show page layout, please read the documentation Page Templates:
https://netmix.com/radio-station/docs/Display/#page-templates

TLDR? You can re-enable legacy show templates in your plugin settings via WP Admin Menu -> Radio Station -> Settings -> Templates tab -> Page Template -> Legacy Plugin Template

Please note in future this is a development forum for bug and features, the support form is found here: https://wordpress.org/support/plugin/radio-station/
