### ISSUE TITLE
[Schedule Override] Prevents Remaining Schedule From Showing on Master Schedule

### ISSUE THREAD

**Issue by Fishy49** [netmix/radio-station#221]
**Describe the bug**
When an override is displayed on the master schedule table, the remainder of the day is lost and shows blank

**To Reproduce**
1. Create a show that lasts all day on a particular day
2. Create a schedule override for 30 minutes in the middle of the day
3. Create a page and display the master schedule table with the shortcode: `[master-schedule list="table"]`
4. Visit the page and notice that the day is blank following the displayed schedule override

**Expected behavior**
The overridden show will pick up where the scheduled override ends.
Otherwise _another_ override will need to be created with the remaining shows manually listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5632528/83048681-9a2fd100-a00f-11ea-87ad-647c165e1327.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser Chrome
 - Version 83

**Additional context**
This expected behavior is what _I_ was expecting to happen.
Another solution may be to add an option that prevents scheduled overrides from showing.

**Comment by tonyzeoli** [comment]
@majick777 Can you look into this, please? Thanks.

**Comment by majick777** [comment]
@Fishy49 I found that the override shift keys were not being cleared between each day in the loop, and this seems to have been causing the issue when there are multiple overrides within the week.

I have added a fix to the development version 2.3.1.3, can you install that version and check if this resolved the issue for you?
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by Fishy49** [comment]
@majick777 I'm still seeing the same thing with the `2.3.1.3` version.

I suppose I should ask the question: if I override only 15 minutes of a 4 hour show, what is _supposed_ to show on the schedule?

I honestly don't know what the right answer is there and was wondering how the plugin was written to handle these instances.

In the older versions (I've been using this for a good long while) overrides just didn't show up on the table (I suppose because it's quite complicated to make work without making a lot of assumptions).

Would appreciate your thoughts.

In the interim - the station manager has been creating overrides to fill in the empty blocks of time. This will hold us for now.

Thank you for your speedy response! We love this plugin - I'm hoping to get some time to put in some PRs of my own!

**Comment by majick777** [comment]
@Fishy49 Okay thanks for checking that,  I will have another go at it then...

You are correct that the previous versions of the schedule display did not honour overrides, so I basically rewrote the entire schedule calculation to be done prior to being displayed, and this was one of the main reasons for doing that. (the Legacy table and Div views still do not honour overrides but the legacy table has been replaced and the Div view may be rewritten in the future into a Grid view.)

What is supposed to happen is that only the portion of the show that is being cutoff should be overwritten, which as you can imagine is a fairly complex set of conditions as the override could start before, at the same time or during an existing show shift... and end before or after an existing show shift. In any case the remainder of the Show should remain, whether it is before and/or after the schedule override.

This seems to be happening fine when I test the overrides, however, I will recheck the code where the show shift start time and override start time are the same... ...okay, no that was fine. 

...I found it with some further debugging though, the problem was with overrides/shifts ending exactly on midnight, since that is "12:00 am" the timestamp returns the start of the *current* day instead of the start of the *next* day, so when the timestamps were checked against each other the remainder of the Show shift was not being set. 

I have added the fix to develop version 2.3.1.4 for 2.3.2 release.

**Comment by Fishy49** [comment]
@majick777 Awesome!! That fixed it right up and it looks great.

Your work on this has been very impressive and the station I work with is loving the attention.

I was worried I'd eventually have to rewrite this thing myself, haha.

Thank you much!
