### ISSUE TITLE
Show Information Panel Missing

### ISSUE THREAD

**Issue by thisisshuffle** [netmix/radio-station#222]
**Describe the bug**
The show information panel is missing from any new or existing show, this stops any new show being added or present show being amended. The schedule is operating and displaying as usual and retaining information previously entered - although this can now not be seen in the admin panels. 

**To Reproduce**
1. Go to 'Dashboard.'
2. Click on 'Radio Station.'
3. Click on 'Shows' and 'Edit'
4. The post type edit page appears but the 'Show Information Panel' does not appear.

**Expected behavior**
A show information panel should appear to enable amendment/entry of show times.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version : Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
I have also tried access via Firefox, disabling all other plug-ins and changing theme, and problem still persists. 
Radio Station Plugin 2.3.1
Wordpress : 5.4.1
Theme : Royale News Version: 2.0.8

![radstation-shuffle](https://user-images.githubusercontent.com/53148877/83063947-e18e7f80-a058-11ea-8192-4b9114eaa6bb.png)

**Comment by tonyzeoli** [comment]
Thanks for reporting this. I can't imagine that's not a plugin or theme conflict. We'll check on our side. Is the theme free or pro? When you disabled the theme and all the plugins, did you do it at the same time, or did you do it separately? Did you try all possible configurations? All plugins and theme. Theme and each plugin individually. Same for new theme? Did you clear your cookies on each try?

**Comment by tonyzeoli** [comment]
@majick777 Have you seen this bug happen?

**Comment by majick777** [comment]
@thisisshuffle Can you click on Screen Options in the top right and see if the Show Information metabox is listed? I can't imagine why it would become unchecked, but that is a possibility.

To debug, you can add `&rs-debug=1` to the URL and view the page source. You should see a section starting with `<!-- DOING TOP METABOXES -->` that lists which metaboxes are hidden on the current screen.

**Comment by thisisshuffle** [comment]
I tried swapping to another theme that I have on another site/station that I also use the Radio Station plugin on.  I disabled all plugins, then brought them back in one-by-one. I am using the free version of the theme.

I have checked the Screen Options panel, and all are checked including "Show Information", I have attached a copy of the source code, the metaboxes tag shows at line 5785

[view-source-thisisshuffle.co.uk-wp-admin-post-php-post.pdf](https://github.com/netmix/radio-station/files/4720445/view-source-thisisshuffle.co.uk-wp-admin-post-php-post.pdf)

**Comment by majick777** [comment]
@thisisshuffle I was unable to reproduce this initially, and then had it happen to me briefly yesterday while working on improving the shift saving interface. It seemed to happen quite randomly after reloading the page. The I realized I had accidentally clicked toggle on a metabox... on further testing, I found it isn't the toggling that caused this, I'd actually triggered the drag and drop of the metabox position order. 

After some further debugging, it turns out the WordPress metabox sort ordering auto-saving does not support the metabox ID having a `-` in it! Which causes the metaboxes to disappear the next time the page is viewed. So simply changing the metabox position ID from `rs-top` to `rstop` seems to have fixed the issue and the metabox sort order saves fine.

I have included this fix in develop version 2.3.1.4 for 2.3.2 release. 

If the metaboxes do not reappear for you instantly, you may have to move one of the other metaboxes on the page to trigger a metabox order resave and then refresh the page. Alternatively, you can reset the positions programattically by adding this code and reloading the page:
`delete_user_option( get_current_user_id(), 'meta-box-order_show' );`
But this probably isn't necessary, as moving a metabox should work fine.
