### ISSUE TITLE
[Shows Archive] Page slug for "shows" conflict

### ISSUE THREAD

**Issue by pozitronios** [netmix/radio-station#235]
This is very strange.
I created a page shows with the same slug and assigned it through the settings to display the shows archive. Because I wasn't happy with the result, I de-assigned it from radio-station settings and manually recreated, keeping the same title and slug.
However it didn't display what i've designed but kept displaying the plugin's show archive. Deleted it then updated the settings in page archives but nothing. When I go to url localhost/mysite/shows, it still displays that show sometimes or redirects to homepage, no 404. The page shows or slug doesn't exist

**Comment by majick777** [comment]
@pozitronios First thing to check would be the page slug of the new page since you recreated it. If it is "shows-2" (which WordPress defaults to if the original page is still in the trash instead of permanently deleted.) - then you either have to untrash the previous page and change it's slug or permanently delete it to be able to change the new page slug to just "shows".

`/shows/` is the default path for show archives, so if there is no page with the explicit slug of "shows" then that will display, so this seems to be the most likely cause.

**Comment by pozitronios** [comment]
@majick777 already done what you suggested, but no. Also tried  a fresh install (on xampp localhost) with just radio station activated created a page shows with the same slug and it displays "Archives: Shows Post type for Show descriptions".  I have set from the settings a different page for show archive pages.

**Comment by majick777** [comment]
@pozitronios Part of the intention of the archive page settings is so that the plugin could optionally redirect from the standard WordPress archive to the chosen page... but since those redirect options are not even implemented anywhere yet, they can't be causing the issue. 

So it must be something conflicting with the standard post type archive and the page. In my experience setting a page slug explicitly always overrides the archive one, so I am not sure why this isn't happening for you yet. You could try saving your permalinks to flush the rewrite rules?

**Comment by tonyzeoli** [comment]
@pozitronios checking with you on status. Please let us know if @majick777 reply was able to resolve your issue.

**Comment by majick777** [comment]
@pozitronios You could try adding this (to a PHP file in /wp-content/mu-plugins/ or in your child theme functions.php)
`add_action( 'init', 'disable_radio_shows_archive_slug', 11 );
function disable_radio_shows_archive_slug() {
    global $wp_post_types;
    if ( isset( $wp_post_types[RADIO_STATION_SHOW_SLUG] ) ) {
        $wp_post_types[RADIO_STATION_SHOW_SLUG]->has_archive = false;
    }
}`
and then resaving your permalinks to flush the rewrite rules.

**Comment by pozitronios** [comment]
@majick777 I added the code to functions.php in my child theme, on new install so no conflicts with other plugins.
Still when no page with slug shows is present I dont get a 404, just an empty page. After creating a page with slug 'shows' it displays an empty page and no content. Currently I am working on xampp on localhost. Perhaps it's just my environment. Have you been able to recreate this?
Thanx

**Comment by majick777** [comment]
@pozitonios Please note customizations like this are typically outside the scope of support. Here is the tested version (again you will need to flush your permalink structure by saving it for this to work):

```
add_action( 'init', 'disable_radio_shows_archive_slug', 11 );
function disable_radio_shows_archive_slug() {
    global $wp_post_types;
    if ( defined( 'RADIO_STATION_SHOW_SLUG' ) && isset( $wp_post_types[RADIO_STATION_SHOW_SLUG] ) ) {
        $post_type_object = $wp_post_types[RADIO_STATION_SHOW_SLUG];
        $post_type_object->remove_rewrite_rules();
        $post_type_object->has_archive = false;
        $post_type_object->add_rewrite_rules();
    }
}
```

The rewrite rules need to be removed and re-added because `add_rewrite_rules` is called in `register_post_type` and so changing the post type object later does not have the desired effect without redoing this.
