### ISSUE TITLE
[Widgets] Current Show and Upcoming Show Widget conflict

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#236]
**Describe the bug**
In Dev version 2.3.1.9, if you have Current Show **and** Upcoming Show Widget on your sidebar, the Current Show widget stops working and displays 'No scheduled show' message. Even though there is a scheduled show. Because if you then remove the Upcoming Show widget, it shows Current Show correctly.

I have also noticed that it takes some time to load the widget.

The same behaviour happens when you use both [current-show] and [upcoming-shows] at the same time.

**To Reproduce**
1. Add both widgets to your widget area (I have been doing it in Sidebar)
2. Set your widget settings as you normally would
3. See live site and you'll see Upcoming Shows display correctly, but Current Show will say nothing is scheduled, despite the fact that it is.

**Expected behavior**
Both Current Show and Upcoming Show Widget/Shortcode should be able to be used together.

**Screenshots**
See attached
![Screenshot 2020-07-04 at 16 54 06](https://user-images.githubusercontent.com/67294458/86516314-74b89300-be17-11ea-891d-b9dae6ec623f.png)

**Additional context**
In Dev version 2.3.1.9

**Comment by majick777** [comment]
@astevens93 This is possibly something in the new AJAX loading of widgets. (The delay is due to the AJAX loading.)
If you don't have a page cache, then you can turn the AJAX loading of widgets off in the plugin settings (or set it on individual widgets if you prefer.) But in any case I will take a another look at the AJAX widget loading code and retest it.

**Comment by astevens93** [comment]
Confirmed that turning off AJAX loading fixes the problem. Thanks!

**Comment by majick777** [comment]
@astevens93 Ok thanks for that, well it is a new feature, so probably best not to have it on by default anyway.
I will have a further look at what could be causing this, perhaps the two widgets are somehow calculating refreshed schedules simultaneously and missing somehow... ah hmmm - this is probably happening since we turned "Clear Transients" on.

**Comment by majick777** [comment]
@astevens93 I have made an adjustment to when the transients are cleared - so they are not auto-cleared for AJAX when the "Clear Transients" setting is on. Feel free to retest the AJAX widgets now and hopefully these changes are sufficient to fix the conflict.

**Comment by astevens93** [comment]
Hi @majick777 - thanks AJAX loading for both widgets running at same time works now!
