### ISSUE TITLE
[Current Show Widget] Non AJAX Widget sometimes says No Show scheduled

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#241]
**Describe the bug**
Very _occasionally_, on a page load, the widget for Current Show (when set to _not_ use AJAX) will fail to load the current show and instead display 'No Show scheduled' text (or whatever the widget text for no show is set to).

Using Dev version 2.3.1.12.

**My question is - is there something that could be causing this?**. Appreciate it is difficult to track down due to its intermittent behaviour.

**To Reproduce**
Difficult to quickly re-produce as it is intermittent and cannot fatham why this is happening. Most of the time it is right but the odd case it will do this.

**Expected behavior**
NON AJAX load will load correctly all the time on every page load.

**Additional context**
On NON AJAX load for Current Show widget. 

I have seen this on MAC OS X Chrome and Safari.

**Comment by tonyzeoli** [comment]
@astevens93 Can you possibly take a screen record with CloudApp or equivalent and post the link, so we can see what the behavior is and how it happens with a video?

**Comment by astevens93** [comment]
Hi @tonyzeoli please let me know if you're able to download this .mov file https://we.tl/t-Qx781NNsrb

I kept refreshing the site multiple times until I got the error. Then as you can see a simple refresh fixes it.

**Comment by tonyzeoli** [comment]
Okay, great. I'll ask @majick777 to review the video.

**Comment by ionuke** [comment]
Also have this problem at our website <www.2nvr.org.au>  "Coming Up" widget displays "No Upcoming Shows Scheduled". In our case, disabling Ajax as default setting and at widget level has no effect. Worked okay for a couple of days. Other visitors have reported this symptoms in Chrome and Firefox, on Mac,  and Edge, Chrome, Firefox using Windows. Using HTML widget with shortcode, same symptom. The problem is constantly present this morning. Have disabled the widget on our homepage, can be seen under navigation "Contact" -> "On Air Announcement Request". Fabulous work on this plugin, by the way. :)

**Comment by astevens93** [comment]
Hi @ionuke interesting you have the same symptom. I was worried it was just me!
I’ve had a look at https://2nvr.org.au/contact/ like you say and I see the same as I get where On Air Now comes up with No Show currently scheduled.  The coming up soon widget loads fine.  Yours seems to throw the error more consistently than mine does though.

![D6FA5F43-6131-457A-8F9A-58B239DC4FE5](https://user-images.githubusercontent.com/67294458/88146697-1b60aa00-cbf4-11ea-9dab-2f520b7a409c.jpeg)

**Comment by majick777** [comment]
@astevens93 @ionuke I have seen this happen occasionally, and suspected it might be due to the Current Show transient expiry. But there is not much point to this transient if it is going to cause these potential problems, so I have just removed this transient entirely, the plugin now just loops the current schedule (which is still a transient but has not had any problems) and gets the current show.

Added to development version 2.3.2.4 for 2.3.3 release.
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by astevens93** [comment]
Hi @majick777 - just to let you know this still doesn't seem to be fixed in Version 2.3.3.1.
Any shows scheduled between 10pm - 12am will always show 'No Show currently scheduled'.

I am getting the same message not only on my site, but http://radiostationdemo.com/widgets/

![image](https://user-images.githubusercontent.com/67294458/88592367-d2767e80-d055-11ea-9768-375251a95185.png)
