### ISSUE TITLE
on turned on V2.3.2 plugin can't publish another customizations

### ISSUE THREAD

**Issue by larryl79** [netmix/radio-station#248]
**Describe the bug**
on turned on V2.3.2 plugin can't publish another customizations
doesn't matter what theme is turned on even on a "fresh installed virgin WP"
all another plugin is turned off

**To Reproduce**
1. Turn on plugin.
2. goto "visit site"
3. click customize
4. edit menus, widgets, custom css etc.
5. click on publish.
6. see error message: "Looks like something’s gone wrong. Wait a couple seconds, and then try again." or "The previous set of changes has already been published. Please try saving your current set of changes again." and not saving what you've done.

7. turn off radio station plugin
8. repeat steps 2-5.
9. no error message.

**Expected behavior**
expecting a quick publish without any error.
**Screenshots**
![image](https://user-images.githubusercontent.com/24578424/88489140-72ff6c80-cf8a-11ea-9722-b5399534bb92.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome, firefox]
 - Version [latest]

tested on 2 different wp installation on 2 different domain.

**Comment by torpix** [comment]
Got the same Issue. since version 2.3.2

**Comment by samsmette** [comment]
I am experiencing the same issue with Elementor not allowing me to publish/update pages. This was caused following the update to 2.3.2.

**Comment by tonyzeoli** [comment]
Hey everyone / this was already reported and the fix is ready for push late tonight EST sometime after 9 pm. In the meantime, disable Radio Station, publish your change to your theme or toolset views, which is also affected), and then reactivate Radio Station. We found and issue in the Ajax Script that conflicted with all themes with post types using a certain function. I will keep open until the updated to 2.3.3. For now, you could also download the dev version and use that to fix this issue until the release. Sorry for the trouble, it wasn’t something we could have anticipated and we weren’t looking for this issue in testing. We have a guide on Netmix in Docs about Ido the dev version. I’m on my mobile and it’s difficult to post the link. You can also see this issue under closed issues.

**Comment by larryl79** [comment]
> Hey everyone / this was already reported and the fix is ready for push late tonight EST sometime after 9 pm. In the meantime, disable Radio Station, publish your change to your theme or toolset views, which is also affected), and then reactivate Radio Station. We found and issue in the Ajax Script that conflicted with all themes with post types using a certain function. I will keep open until the updated to 2.3.3. For now, you could also download the dev version and use that to fix this issue until the release. Sorry for the trouble, it wasn’t something we could have anticipated and we weren’t looking for this issue in testing. We have a guide on Netmix in Docs about Ido the dev version. I’m on my mobile and it’s difficult to post the link. You can also see this issue under closed issues.

https://github.com/netmix/radio-station/releases/tag/2.3.3

**Comment by larryl79** [comment]
bug solution in last 2 post. confirmed V2.3.3 tested and working fine.

**Comment by tonyzeoli** [comment]
@larryl79 Thanks. 2.3.3 just deployed on the WordPress plugins page.
