### ISSUE TITLE
Bullet Point on Title

### ISSUE THREAD

**Issue by Aaronjacobs678** [netmix/radio-station#267]
![snip](https://user-images.githubusercontent.com/61187426/92144040-063f8380-ee0e-11ea-83a7-a0e72965f7a1.png)

Evening - Using the [current-show] shortcode and I am really struggling with this bulletpoint from the <UL> the 'title' is sitting in. Is there a quick way to remove? I have been sat adjusting styles, adding tags and trying to locate where the 'UL' code is coming from. But cannot find it anywhere!

Please put my mind to rest, haha!

Thanks,
Aaron 👍

**Comment by tonyzeoli** [comment]
Sorry we haven't responded yet. I'm waiting for @majick777 to come around to your issue. He's best able to resolve. I understand it's frustrating, but I ask for your patience until he can get to you. He's in Australia and due to Covid-19, we are doing our best to deal with our personal issues while resolving support issues. Thanks for your understanding. I'll ping him on Slack again and ask him if he can get around to this.

**Comment by majick777** [comment]
@Aaronjacobs678 The code for this shortcode is found in `/includes/shortcodes.php`

This isn't a bug, as the plugin already has the CSS in place to remove the disc style:
`.current-show-list, .current-show-list li {list-style: none;}`
It is probably the case that your theme is overriding this with another rule. 

Try adding this more specific CSS:
`ul.current-show-list, ul.current-show-list li.current-show {list-style: none;}`
This should hopefully override whatever is causing the style conflict.

**Comment by Aaronjacobs678** [comment]
Thank You so Much! I really tried trawling through my CSS that I have written by hand... But could not find any conflict. Not sure if bootstrap has something to do with it?... BUT you have resolved my problem.. with Style! Haha!

Thank you so much!

**Comment by majick777** [comment]
@Aaronjacobs678 haha you're welcome. 

Instead of trawling your existing CSS you always right-click and "Inspect Element" in most browsers and there will be a list of styles on the bottom right window applied to that element from various stylesheet sources, and you can see which ones are being applied and which ones overridden (crossed out.)
