### ISSUE TITLE
Master Schedule Shortcode  link-hosts on Show page

### ISSUE THREAD

**Issue by KerryB1** [netmix/radio-station#271]
When the Short Code Link_hosts is used on the Master Schedule it successfully turns on ( or off) the link to the DJ/Host profile page  on the main schedule entries.    However, it does not turn off the link to the DJ/Host profile page on the Show page.
Not sure if this is the expected behaviour, however, if it is, then it would be useful to turn off both the DJ/Host links

To recreate.
Set the Link_Hosts shortcode in MAster Schedule to On and the DJ/Host profile links  work on both schedule and show page
Set the Link_Hosts shortcode to off and the DJ/Host profile link on the schedule is stopped, but it still links on the Show page

We are not currently providing full DJ/Host profiles as this info is held in our Show pages, and consequently a Page Not Found error is created if a user follows the DJ/Host link

**Comment by tonyzeoli** [comment]
So sorry for the delayed reply @KerryB1 Been working on some client projects last week but am coming around today to check on tickets.

I can see why that would be an issue. If you're turning off the link on the calendar, then the link should be turned off on the Show Page too.

We'll check into this and get back to you.

**Comment by majick777** [comment]
@KerryB1 There is a filter in `radio_station_get_host_url` which you can use to disable all host links:

`add_filter( 'radio_station_host_url', '__return_false' );`

This can't be done through the Master Schedule shortcode because there is a separate template for single Show pages. Also this filter will disable linking in the Current and Upcoming Shows widget as the function is also used there.
