### ISSUE TITLE
[Schedule] Tabbed View only Displaying Show Images

### ISSUE THREAD

**Issue by judeconnors** [netmix/radio-station#275]
The tabbed view of the schedule no longer shows any of the information, just the pictures.

You can see this by checking my page: https://xradio.zone/schedule/

![Screenshot_6](https://user-images.githubusercontent.com/66576662/97356566-74c91c80-1866-11eb-8a21-4ba543974c8e.png)

**Comment by tonyzeoli** [comment]
@judeconnors I took a look at the page you referenced and you've switched out of the tabbed view, so we can't ascertain what your issue is. If you look at the demo site here; [](https://radiostationdemo.com/master-schedule/tabbed-view/) there are no issues with the display of the content to the right of the thumbnails. Until you are able to restore the tabbed view, it's going to be difficult for us to assess what your issue is.

**Comment by majick777** [comment]
@judeconnors I recommend installing the latest development version that is pending release to see if this resolves the issue, and if not create a separate page that we can still preview on your site.

https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by judeconnors** [comment]
Updated and now it works again. Thanks!

**Comment by majick777** [comment]
@judeconnors Great! :-)
