### ISSUE TITLE
[Schedule Page] Template and Theme configuration

### ISSUE THREAD

**Issue by Dexbowen** [netmix/radio-station#279]
Hi,

I selected the page I want the schedule to display on and in the setting the Theme template is selected but when the scheduled is displayed on the page it is outside the specified area. It pushed the sidebar to the bottom of the page.

I am expecting the schedule to sit within the dark section of the page as the rest of the site  and not on the background.

![image](https://user-images.githubusercontent.com/3705265/98558490-7be32800-2273-11eb-8f9c-3d3259d055ff.png)

![image](https://user-images.githubusercontent.com/3705265/98558420-6241e080-2273-11eb-9dee-a462f3ce16db.png)

![image](https://user-images.githubusercontent.com/3705265/98558554-91f0e880-2273-11eb-9728-49611b5cdfb4.png)

Second issue is I created only one show schedule and I am getting conflicting schedule error. How is that possible when its only created for one day and only a single time slot? There are no other shows or time slots created.

![image](https://user-images.githubusercontent.com/3705265/98565395-91f4e680-227b-11eb-9ade-a723aa75aa46.png)

The schedule page is not published since the issue is pending. Let me know how I can add the screenshots if they do not display.

Thanks

**Comment by Dexbowen** [comment]
I was able to resolve how the schedule displayed on the page by unchecking the automatic display box.
![image](https://user-images.githubusercontent.com/3705265/98565747-f87a0480-227b-11eb-8164-377ef9d69f8c.png)

The issue is now, I am unable to display the schedule with tabs. Is this by design?

**Comment by tonyzeoli** [comment]
@Dexbowen sorry to not get back to you quickly. @majick777 can you address this?

**Comment by majick777** [comment]
@Dexbowen Which theme are you using? Schedules are output via shortcode and the settings are available with the intention of being able to play nicely within any theme, but from what you've said it looks like it's not working as intended with your theme, so to investigate further I'll need to check with that theme to determine whether there is a conflict there or if it's some more general bug.

**Comment by majick777** [comment]
@Dexbowen Also note for now, if you uncheck `Automatic Display` option, you need to include the shortcode in the page, eg. for tabbed view: `[master-schedule view="tabs"]` ... The Schedule should be showing at all without that checked and without the shortcode in the page content.

**Comment by tonyzeoli** [comment]
@Dexbowen and @majick777 I'll leave this open for 72 hours and if we don't hear back, we'll close this ticket as resolved.

**Comment by majick777** [comment]
@Dexbowen I suspect there is something in the theme's `page.php` template that is closing one too many HTML tags when there is shortcode content, so the content/sidebar container is closed and the sidebar pushed out of it... But again it's hard to tell without being able to see the page source or test the theme, so if you could provide an URL and/or name of theme, otherwise we may not be able to test/resolve this further.

I also see an "Edit" link there which _could_ be causing the issue if it has one too many closing tags. As these usually show to logged in Admins only - you can test this by viewing the page in a logged out browser to see if it still is broken or not. Again only a possibility.

**Comment by Dexbowen** [comment]
Hi All,

Sorry for the late response. I am using the Pratt theme.

[image: image.png]

**Comment by Dexbowen** [comment]
![image](https://user-images.githubusercontent.com/3705265/99709519-49081380-2a6d-11eb-8d41-b7e34c24d006.png)

The Url is www.purevibesradio.com

**Comment by Dexbowen** [comment]
Hi Team

You can login with the below information to check. The Page is not
published so you can click on pages in the dashboard and look or show &
schedule.

www.purevibesradio.com
Username - admin
PW - MyFamily712 or MyFamily716

**Comment by majick777** [comment]
@Dexbowen Please don't post your login details in public forums, it's a security risk. We can't be responsible for what might happen and I suggest you change the password now.
If you need to provide login details at some stage, you can request an email to send them to. 
I'll download this theme from the repository and check it locally as a first step to see if there is a conflict.

**Comment by tonyzeoli** [comment]
Or, you can set one of us up as a user at our email address and prompt the
complete registration process. Or, register one of us or a dev account and
like Tony said, email us the credentials. I'll confirm that one shouldn't
post login credentials in a public forum like Github.

**Comment by Dexbowen** [comment]
I thought I was responding privately. Is there a way to remove that post.

**Comment by tonyzeoli** [comment]
You should be able to edit it yourself or just change the password.

**Comment by Dexbowen** [comment]
Hi, So the only way I was able to accomplish what I am looking for is by placing shortcodes in the page and unchecking automatic. Please see the images below:
![image](https://user-images.githubusercontent.com/3705265/99806122-84f1b600-2b0b-11eb-8353-7e66a8f8375f.png)
![image](https://user-images.githubusercontent.com/3705265/99806176-9dfa6700-2b0b-11eb-8b3a-e447a7811a24.png)

![image](https://user-images.githubusercontent.com/3705265/99806249-bec2bc80-2b0b-11eb-9fbd-e5b472bfb982.png)
![image](https://user-images.githubusercontent.com/3705265/99806286-cd10d880-2b0b-11eb-9f95-15ac160ed5ef.png)

**Comment by Dexbowen** [comment]
![image](https://user-images.githubusercontent.com/3705265/99806467-0e08ed00-2b0c-11eb-847c-8fe53ca390d5.png)

**Comment by Dexbowen** [comment]
Hi Team,

I sent an email to majick777 <notifications@github.com> with credentials to
access the site. Let me know if you received it.

Thanks

**Comment by tonyzeoli** [comment]
@majick777 I don't want to post your email publicly. I think notifications@github.com is incorrect. Let @Dexbowen know how you want to get the credentials.

**Comment by majick777** [comment]
@Dexbowen So as it turns out, the parent theme to Pratt - Flat Bootstrap - has an early filter on `the_content` to add a an after-content element... While this is a little unusual, but not outside of what a theme could be doing. Since the automatic pages replaces the content entirely (also via `the_content` filter), this element's opening tag was being stripped, but not it's closing tag, causing the container to be closed early instead and pushing the sidebar outside of it. 

To resolve this without affecting other themes, I have buffered the shortcode and cleared the content even earlier for automatic pages and then output it later... this preserves any filters that are in between. 

Well never mind if all that may be too technical, I've included this fix in the latest develop branch for release:
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by Dexbowen** [comment]
Hi That was a little technical but understandable lil!

Thanks for the update.

One question, is it possible to have the option to display upcoming shows
horizontally on the page?  Can it also apply to the Tabbed weekly schedule.
I know for me it would flow well with the design especially on a full width
page.

example:

Monday
Show          Show         Show

Upcoming shows
Show          Show         Show


The site currently looks like the below image and it does not flow with the
other elements on the page.
[image: image.png]

**Comment by tonyzeoli** [comment]
That's like the cable TV schedule on your cable box - where its a scroll to the right, as well as up/down

SHOW NAME then SHOW TIMES across like below.

............................7PM.............8PM.............9PM
EX: NETMIX    Episode 1.      Episode 2.     Episode 3.

You'd then have to scroll to see the complete 24-hours, because it probably won't fit in smaller viewports.

**Comment by Dexbowen** [comment]
Hi Netmix/Radio-Station,

Sorry to bother you again. The streaming player does not show even though
the URL in setting is populated.

Please advise.

**Comment by majick777** [comment]
@Dexbowen Currently you would need to add your own CSS styling to either Tabbed or List view to get the horizontal Shows. We do plan to add a Grid View in the future as part of the Pro version.

The Streaming Player URL setting is currently only to make your Stream discoverable via the Data API. The actual streaming player itself is what I am currently working on as a top priority for the next main feature of the plugin (slated for 2,4.0,) As of writing this we are close to releasing a bugfix version 2.3.3.6, but once the player is ready and working we will just bump to 2.4.0 and release it. :-)

**Comment by Dexbowen** [comment]
Thanks for the update.
