### ISSUE TITLE
[Schedule] Style classes for 'past shows' for each day

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#283]
**Is your feature request related to a problem? Please describe.**
No specific problem, just a feature request.

**Describe the solution you'd like**
On tabbed schedule, would it be possible to have the option of hiding the previously broadcast shows for that day?

Currently it looks like this:
![now](https://user-images.githubusercontent.com/67294458/100481418-f32a1000-30eb-11eb-9c33-8be631e9ed02.png)

But it could look like this...
![request](https://user-images.githubusercontent.com/67294458/100481428-f91ff100-30eb-11eb-993f-afe4a64fe7d1.png)

**Additional context**
This may not be possible as additional classes might have to be added which won't be desired by all users.
Just a thought and something our radio station desires, but it is not essential if it is not deemed necessary for the wider project.

**Comment by tonyzeoli** [comment]
That’s a good idea for a feature request, but I’m thinking it’s best to gray out the passed shows so they are slightly faded, because there are always going to be people who want to see the entire days schedule.

Alternatively, they could disappear and have a view all shows that transpired today link to toggle between all and shows that ended.

But just hiding them with no ability to see the lost for the day might be an issue if the viewer wants to see the schedule for the day for some reason. Also, when we get to Episodes, they will display the Episode ID - whatever that is and when they comes into play, someone might be looking on the schedule for a show that happened earlier in the week.

Did you consider these issues when thinking this through?

**Comment by tonyzeoli** [comment]
@majick777 What are your thoughts about this feature request from @astevens93. i like the idea of greying out completed shows on the present day on the tabbed schedule so that they are still visible but the greyed out means the shows aired in the past and are now completed.

We don't want to hide them completely, because then someone can't click on a show and get to the show page. So, we might want to add a button for 'Show Info" or something like that, which is not greyed out in any case, so that the user can click the Show Info button even if the container for that show is greyed out.

An additional element to this would be to add a toggle where the default is to grey out all completed shows, then you could filter the list to see only the shows remaining for the day

We have to consider whether this is a free or PRO feature.

**Comment by astevens93** [comment]
Hi @tonyzeoli apologies for my tardiness in coming back to you. I absolutely agree now you've said it regarding your comment of people wanting to see shows for that day, and hiding them would make that not possible to do.  Thanks for expanding my thoughts.

Greyed out seems like a good option, though I actually wonder on the demand for this.  I might be an isolated case for this request.

One I'm happy to put on the back burner unless @majick777 does believe it's an easy request to implement.

**Comment by tonyzeoli** [comment]
@astevens93 You're the only one who has asked for this, so there's no specific demand for this, but I think it's a neat feature and something that we should do. Whether we grey it out or put a marker on each entry to denote it's a completed show, it's a good suggestion for the list view and even the table/grid view. it does make the system feel more dynamic and it helps the user focus on the current time. This could be in some combination of free/PRO whereas we might just put a marker on completed shows in free and then grey it out in PRO with a toggle to see all shows or upcoming shows minus completed shows, Not sure yet, but I like the concepts.

**Comment by majick777** [comment]
@tonyzeoli @astevens93 For now we can just add the classes so they are available for style targeting. As I've just updated the show highlighting code (for #255) this is fresh in my mind... it was easy enough to make some changes there and add a `before-current` and `after-current` class to other Shows in the schedule.

But we can continue the discussion on how this could be used further...  I think one possibility here could be a checkbox above the schedule with a "Hide Finished Shows" label (that could be added via shortcode attributes) as a Pro feature? If we think this it significant enough that it would be used.

I haven't added any default styling to past Shows yet... We could maybe add some transparency (reduced opacity) to them so they are "greyed out" a little in that sense? (as we can't really use grey or colours for this as it could too easily conflict with a theme/user colour scheme.)

**Comment by tonyzeoli** [comment]
"Reduced opacity" is the better term. Agreed that "greyed-out" is not the correct analogy here. Let's go with reduced opacity for completed shows. A check box there would be good to hide finished shows if someone just wanted to see all upcoming shows - could that be based on a cookie setting where it's always that way for that user when they return to the site?

**Comment by astevens93** [comment]
Hi both, I absolutely agree 'reduced opacity' is a good way to go.

I think it would be both user and admin preference.  The average front end user might not think about toggling past shows to be hidden, but perhaps they would be for ease of viewing. So the ability to set this as default by admin either in shortcode of template file would be good.   If the toggle part on the front end is wrapped in an individual class, then it can easily be hidden by CSS by the admin if they chose to set it by default for all their web users.

**Comment by astevens93** [comment]
To note my original request has been achieved now visually through adding the CSS below. Thanks to @kairandles for the contribution.

```
.before-current {
display: none
}
```

There were a few other considerations that pursued my request in the comments section, so @tonyzeoli if you wish to close this because my specific request has been answered, or if you would like to keep open because of the other features discussed, will leave this with you.

**Comment by tonyzeoli** [comment]
@astevens93 I think we need to include this as an admin function, so that users can show/hide based on their use case, so even though there's a CSS solution, I'd like to keep it open and add it so we don't keep getting the same request and have to support that all the time by educating people on how to do it. It should be part of the free plugin. I think that's a neat feature and we'll just go with it.

**Comment by majick777** [comment]
@tonyzeoli @astevens93 I've added the reduced opacity style (of 0.8) to the stylesheet for past shows using the `before-current` class. 

Rather than being an admin option to hide past shows, or only doable by CSS, I think the middle ground is to add this as a shortcode attribute. So `hide_past_shows="1"` will add a `hide-past-shows` to the tabs panel div and individual past shows will disappear when they have the `before-current` class. 

Personally I wouldn't hide past shows as it reduces Show discoverability for the coming week, but understand the how it does improve the "nowness" of the schedule by having the current Show appear first.

**Comment by astevens93** [comment]
Thanks @majick777 that sounds like a great solution.  For those with PRO in the future I guess hiding past shows would work nicely because the user would be able to view over 7 days in the future.
