### ISSUE TITLE
2.3.3.7 Release

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#293]
This ticket is to schedule the 2.3.3.7 release.

- Update the version number
- Update Changelog.md
- Update the update notification in readme.txt
- Update the Changelog in readme.md
- Commit development version to master

**Comment by tonyzeoli** [comment]
@majick777 Can you commit the development version to Master and I can then schedule it to push tomorrow, please? Thanks.

**Comment by majick777** [comment]
Because this is a bugfix version, I think we leave out the Upgrade Notification section for it. The reason for this is we have it set up to show an actual Admin Notice if there is an Upgrade Notice, and that is really more for Feature notifications - it could get annoying to the user if they are constantly seeing these notices just for fixes all the time. Of course the version changes will still be listed in detail on the Plugins page in any case.

**Comment by tonyzeoli** [comment]
@majick777 Okay, we'll go with that then. Should we just have a "Check the Plugins page on WordPress.org for a list of all changes" as the notification? We don't want to leave anyone in the dark, so to speak. Someone might want to know, so it's better to give some indication then none as to what happened, because someone might be experiencing one of the issues and it will give them impetus to check first before reporting, maybe????

**Comment by tonyzeoli** [comment]
@majick777 I figured out how to merge develop with master using git gui. One thing i noticed was the package version wasn't updated to 2.3.3.7. Not sure that's required, but updated it anyway and committed that to the WordPress plugin repo. But, I'm not seeing the update in the plugin yet on local or on the demo site.

**Comment by tonyzeoli** [comment]
@majick777 I think I figured it out. Just had to commit to master from my local and that helped things along. The release it now completed.
