### ISSUE TITLE
[Tabbed Schedule] Change Request

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#305]
So, when I display my tabbed schedule view 

- Firstly the past day's don't update (in terms of weekly schedule overrides) until the whole week starts again on Monday where it then refreshes, as soon as the day is over can it refresh to the following week's schedule.

These next ones could be worth (if possible) being used as a sort of 'dynamic tabbed view' VERY similar the schedule on heart.co.uk and capitalfm.com and if added I would look at upgrading to the pro version of your plugin depending on pricing as we are a charity station but I would love to see this on my website

- So first change with the possible new 'dynamic tabbed view' can the day that it is be the first on the tab, this indicates to the user that if they change the date to one of the ones in front it's in the future on in the past 

![image](https://user-images.githubusercontent.com/77554122/104824705-0cc61900-584c-11eb-800d-ecdbee47b475.png)

- Next one all the shows before whatever show is currently live be deleted on this view for that day so that the currently live show is the at the top rather than having to scroll down to find the one highlighted in red

![image](https://user-images.githubusercontent.com/77554122/104824683-dd171100-584b-11eb-86ea-60b4ad39cfc8.png)

- The addition of a customizable play button, (So having just a simple play symbol and custom text all the way up to uploading a custom image) I would want though the ability to make where it links to completely custom with HTML and I would need to to open my player in a popup window, onto the show that is currently live to indicate to the user an easy way to hear the show that is currently on air

![image](https://user-images.githubusercontent.com/77554122/104824728-57e02c00-584c-11eb-9ab0-c32b5bdb85ad.png)

- Changing the layout so it is basically the same as the one in this screenshot allowing me to use a transparent image as the presenter icon
- With this possible layout change can the functionality of a 'Short Description' be added for the area underneath the time, title, DJ / Host
- The only change I would make to how this layout is displayed is also adding the option of displaying the DJ / Host under the title

![image](https://user-images.githubusercontent.com/77554122/104824736-6a5a6580-584c-11eb-9167-29a13d972e72.png)

- The possible addition to this of also allowing a 'date searcher' somewhere like in the top right above the tabbed days for looking at dates in the future so things like schedule overrides would show up

- Also the addition of a new widget/shortcode that is meant for website headers similar to this (maybe even including the two custom links??)
- 
![image](https://user-images.githubusercontent.com/77554122/104827102-4ac63b80-5852-11eb-8db2-6bb2c0f86a3c.png)

**Describe alternatives you've considered**
I use the normal tabbed view currently but som things with it have been really bugging me

**Additional context**
Hope some of these make sense (if not please just ask) and you would be able to say whether or not you think some or all of these things would be possible additions to either the free or paid plugin versions

**Comment by astevens93** [comment]
Hi @kairandles I thought I would respond to this, as I am a heavy user of the plugin and have made some custom CSS styling to the plugin to suit my needs, some of which covers your questions as above. I hope you find it useful.  Some of the other stuff is development so will leave that to the two Tony's to respond to.

Firstly, much of what you want to do can be achieved through the various shortcode attributes that @majick777 has kindly implemented from months of feedback from other users (myself included!).

You can find this list here, https://netmix.com/radio-station/docs/Shortcodes/ - this should be a great starting point.

**Your first point on showing today's date first highlighted, then the other 6 days in advance**
This can be done easily by just adding start_day="today" to your shortcode.

**Second point around hiding shows already broadcast on a particular day**
This has been raised and discussed in detail on issue #283. I requested it as a feature, and it's being considered for the future I believe.

**Customisable Play Button**
Agree this could be a feature request, possibly for Pro.  I achieve something similar using CSS before/after pseudo elements, though as CSS is limited to content rather than HTML links, I cannot achieve a link to open up a player. Adding in 'On Air Now' satisfies us for now.

A Pro feature in the future like this would be handy.

**Changing the layout**
This can be amended by overwriting the CSS of the plugin. There is some info on https://netmix.com/radio-station/docs/faq/ on where the override file can be placed, or like me, you can use Wordpress' inbuilt customiser CSS tool to do this.
It took some doing, but Google Chrome Dev Tools helps speed up the process.

**Date searcher suggestion**
This was discussed on an earlier, now closed, issue, and I believe something like this is in the roadmap for forward dates, much like a calendar so schedules can be viewed way in advance of the 7 day period.

**On air now widget**
There is already an 'On Air Now' shortcode in the plugin (see here http://radiostationdemo.com/extra-shortcodes/current-show-widget/). Again, you should be able to use CSS to help change this around to suit your needs.  I have managed it, and like the schedule, once you work out the classes you need to manipulate, it can be done quite easily. 

As I say, forgive me for jumping in, @tonyzeoli and @majick777 are the project owners and developers, I am a heavy user so have worked through a lot of the customisations with the continued support of both Tony's. 

I hope what I've said is welcome though for now. The bare bones of what you want to achieve are there I believe, but will need some tinkering your end via CSS to achieve close to what you want.

Hope that helps.

**Comment by kairandles** [comment]
Hey @astevens93 I appreciate the comments, this was my feedback on what you have said that I think I can change about the way it's displayed currently before @tonyzeoli and @majick777 can jump in and see if they can do the extra bits!

**Showing today's date first highlighted, then the other 6 days in advance**
Thanks for this! This has been rectified on my site.

**Hiding shows already broadcast on a particular day**
Ah I see, yes it would be great for that to be added but by the look of it they were just going to grey it out rather than remove it. It would be great to at least have the option if this is deemed as 'developable' by the devs!

**Customisable Play Button**
Can I ask for a bit of support with this as I would like to do a bit of custom CSS on this, do you think you would be able to give me some pointers as I'm not the most confident with CSS I normally stick to just editing the HTML

**Changing the layout**
Same as above would you be able to point me in the right direction with what to change/update?

**Date searcher suggestion**
Ah I see, yes it would be great to see as we have a month-long schedule rather than a week so I'm using schedule overrides for the shows that don't repeat weekly but I now have had to add a google calendar embed underneath the schedule on the site as I used to get a dozen emails a day asking when a certain persons show was!

**On air now widget**
Yes I did see this and we use it in our header and footer I was more pointing to the fact of having my stations play button and two their customizable links in it too as at the moment it's a bit more annoying to find the play button

But as I say I do really appreciate the comment as I think this could help to be a temporary solution before it gets improved hopefully by the devs!

**Comment by tonyzeoli** [comment]
Hey @kairandles and @astevens93 I'm just reading through this ticket and see Alex has helped out with some guidance. In the future @kairandles, please separate out your feature requests into separate tickets, so that I can parse them and add them individually. Lumping them all together just serves to make more work in moderating these requests. I've added @majick777, who is the lead developer on Radio Station, to this ticket so that he can view the asks and Alex's replies. I'm wading through it now to better asess and follow up to Alex's comments.

**Comment by kairandles** [comment]
Hey @tonyzeoli, this was how far I got with CSS (thanks @astevens93), I will submit those tickets of things that I still can't change individually now for you!

Just to note these are the things CSS solved: and the scripts of how they were resolved if someone looks at this thread in future

**Showing today's date first highlighted, then the other 6 days in advance**
I missed the shortcode but I just added start_day="today" to it.

**Hiding shows already broadcast on a particular day**
I used a simple css script to hide anything in the 'before-current' class'
<style>
.before-current {
display: none
}
</style>
**Customisable Play Button** - Half fixed
Thanks, @astevens93 I looked at your website and slightly repositioned it for my use case. This was the CSS used to achieve a non-clickable button,
.master-schedule-tabs-panel .master-schedule-tabs-show.nowplaying div.show-info:after {
    content: "On Air Now";
    position: relative;
    display: block;
    background: #b23538;
    color: #fff;
    font-weight: bold;
    margin-top: 10px;
    margin-bottom: 10px;
    width: fit-content;
		width: -moz-fit-content; /* for Mozilla Firefox Compatibility */
		padding: 5px 10px 5px 10px;
		border-radius: 5px;
}

This can also work on the widgets as seen below with this CSS
![image](https://user-images.githubusercontent.com/77554122/104966599-38c2d500-59d9-11eb-8cec-1454d65fbb9d.png)

.primary-footer .current-shift:after {
    content: "On Air Now";
    position: relative;
    display: block;
    background: #b23538;
    color: #fff;
    font-weight: bold;
    margin-top: 10px;
    margin-left: 163px;
    width: fit-content;
   height: 35px;
	  font-size: 15px;
		width: -moz-fit-content; /* for Mozilla Firefox Compatibility */
		padding: 5px 10px 5px 10px;
		border-radius: 5px;
}


![image](https://user-images.githubusercontent.com/77554122/104966339-8e4ab200-59d8-11eb-87eb-f9bdc0151561.png)


Thanks all and I'll open those tickets now!

**Comment by tonyzeoli** [comment]
@kairandles Awesome, thanks for all of this. Maybe this is a blog post I can get out on our blog this week.

Also, I think we should add the option to right-align or left align the image in the tabbed view for those who don't want it on the left but on the right. I'm adding that as a ticket to the free version now.

**Comment by tonyzeoli** [comment]
@kairandles added #https://github.com/netmix/radio-station/issues/307

**Comment by tonyzeoli** [comment]
@kairandles in the free version, we'll always have just the 7 day calendar. In a future version of PRO, we'll have a GCal like Calendar to plan out shows on a full calendar. But that is not planned for the first release of PRO. You'll have to wait on that for a bit, as it's a big task to write it and then if someone were to upgrade, ensure we don't break anything with the current calendar. There will also be a front end editing option of the schedule, as well.

**Comment by tonyzeoli** [comment]
@kairandles I see you are suggesting adding last played song and schedule to the widget for On Air Now. That's not a bad idea, either. I'll add that to the cue.

**Comment by kairandles** [comment]
> @kairandles in the free version, we'll always have just the 7 day calendar. In a future version of PRO, we'll have a GCal like Calendar to plan out shows on a full calendar. But that is not planned for the first release of PRO. You'll have to wait on that for a bit, as it's a big task to write it and then if someone were to upgrade, ensure we don't break anything with the current calendar. There will also be a front end editing option of the schedule, as well.

Hey @tonyzeoli, Great to hear it's on the roadmap! We start broadcasting in December do you think it will be close to or be finished by then?

**Comment by kairandles** [comment]
> @kairandles I see you are suggesting adding last played song and schedule to the widget for On Air Now. That's not a bad idea, either. I'll add that to the cue.

Great thanks! Would be good to see but again if it can be built-in I would love it to be customizable to whatever URL I would like that would be appreciated!
This is open in #310

**Comment by tonyzeoli** [comment]
@kairandles You already have a link to the Playlist in the On Air Now Widget, but you want Last Track Played...that's something we'll have to think about, because that's a specific request to your use case and not something anyone else has asked for.

**Comment by astevens93** [comment]
Hi @kairandles glad you were able to see my CSS and it guided you to what you needed to achieve, I've looked at your site and looking good!

I've just borrowed your code too for hiding previously displayed shows - a complete oversight me not realising that a simple look into the classes would have achieved my request for #283

```
.before-current {
display: none
}
```

Nice work!

**Comment by kairandles** [comment]
> @kairandles You already have a link to the Playlist in the On Air Now Widget, but you want Last Track Played...that's something we'll have to think about, because that's a specific request to your use case and not something anyone else has asked for.

Sure, if not the custom play button would still be good!

**Comment by kairandles** [comment]
> Hi @kairandles glad you were able to see my CSS and it guided you to what you needed to achieve, I've looked at your site and looking good!
> 
> I've just borrowed your code too for hiding previously displayed shows - a complete oversight me not realising that a simple look into the classes would have achieved my request for #283
> 
> ```
> .before-current {
> display: none
> }
> ```
> 
> Nice work!
> 

Great, glad it helped you out. Any chance you could share how you managed to do your CSS? Particularly the scrolling day bar on mobile and the removal of the outlines and setting the custom colours for the active days. I can't seen to figure that one out?

**Comment by tonyzeoli** [comment]
One can only hope, lol. We took over the plugin as is and this is a new
concept to build, but it's on our roadmap and hope to have it by June.

**Comment by kairandles** [comment]
Haha sounds good! Thanks

**Comment by majick777** [comment]
@kairandles There is quite a few things here, thanks to @astevens93 for addressing many of them sooner. As @tonyzeoli says, it is easier to have separate tickets for each request, however I guess it does make sense in this case to list all these here so we can first identify what is already available... as some of these have been answered or resolved I'm just going to sum up here to make sure nothing has gone missing and we can close this out:

- Start of week to today using shortcode attribute `day="today"`
- Hiding of past shows on Tabbed Schedule (#283)
- Custom Play/Listen Button/Links on Tabbed Schedule (#306)
- Custom Play/Listen Button/Links on Current Show Widget (#310)
- Add Shortcode Attribute to have Right Aligned Image (#306)
- Week Change / Date Selector (#309)

What was not mentioned here yet is you can already have a "Short Description" output on the Tabbed View by adding the `show_desc="1"` attribute to the shortcode.

Since these each have their own individual issues now I am going to close this long one here. If I've missed something can we make an individual issue for it so we can prioritize further.
