### ISSUE TITLE
[Tabbed Schedule] Right Align Featured Thumbnail

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#307]
**Is your feature request related to a problem? Please describe.**

A user requested to Right Align the featured thumbnail in the tabbed view.

**Describe the solution you'd like**

Maybe we can add a filter to right-align the featured image and add that to the docs.

**Describe alternatives you've considered**

N/A

**Additional context**

See: #https://github.com/netmix/radio-station/issues/305

**Comment by majick777** [comment]
@tonyzeoli I've added a shortcode attribute for the `[master-schedule]` Tabs view of `image_position`, which defaults to `left` but can be set to `right` - or `alternate` will alternate the thumbnail left-right (something I like the look of for archive templates with thumbnails so I thought I'd add it.) So that should solve this one. :-)
Added to development version for 2.3.3.8 release.

**Comment by kairandles** [comment]
Sounds good, I'll get the dev version installed and will have a play!
