### ISSUE TITLE
[Tabbed Schedule] Layout Options

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#308]
**Is your feature request related to a problem? Please describe.**
A new layout to provide me with the ability to use shoulder up transparent images of presenters

**Describe the solution you'd like**
I would like new layout if possible to allow me with shoulder up presenter images looking a lot cleaner on my site
With this possible layout change can the functionality of a 'Short Description' be added for the area underneath the time, title, DJ / Host

So, in terms of heading on the left it would look like:

**Describe alternatives you've considered**
CSS however didn't get very far...

*Show Title*
*Host / DJ*
*Time*
*Short Description*
*Listen Live Button*                                                                                       *Presenter Image*
--------------------------------------Custom Line Colour --------------------------------------------

**Additional context**
![image](https://user-images.githubusercontent.com/77554122/104967122-855ae000-59da-11eb-9576-bdd91c3ac1b8.png)

**Comment by tonyzeoli** [comment]
@majick777 If we can add the Show Short Description to the tabbed view, that would certainly be helpful. Never thought of that. Good idea by @kairandles. 

@kairandles I think we can add a filter to give you the right align layout option, but it won't be a clickable feature in the plugin. You'll have to add it in a functions.php file in your child theme, I believe. But @majick777 can confirm.

**Comment by majick777** [comment]
@kairandles With the addition of the section filters and section order filter now in the Master Schedule Views (and Widgets) you should now be able to do just about anything, by adding/removing/replacing any section or re-ordering existing sections.

@tonyzeoli The Short Description has already been added for Tabbed View. Because the width of the Show info is not that large, it actually displays in it's own section, inline and to the right.
