### ISSUE TITLE
[Show Page] Add alt tag to download link for accessibility

### ISSUE THREAD

**Issue by matzuras** [netmix/radio-station#313]
In the show page, directly beneath the heading is an unlabeled download link. Please add an alt tag for screenreader users to hear a message such as "Download this program," etc.

**Comment by tonyzeoli** [comment]
@matzuras Good for accessibility. Sure, I'll see if we can get this in the next release this week.

@majick777 Can you add this when you get a moment. Thanks.

**Comment by majick777** [comment]
@matzuras Since the icon is a `span` tag, rather than adding an alt attribute to it, I've added a `aria-hidden="true"` to the span tag and a `aria-label="Download Latest Broadcast"` to the `a` tag that contains it. From the examples I can find this seems to be a better approach since the icon itself is not an `img` tag.
I've also done similar for the Home, Email and Phone icons on the Show page. 
Added the to develop branch for next release.
