### ISSUE TITLE
"Encore Presentation" checkbox on Show schedule

### ISSUE THREAD

**Issue by WBFYradio** [netmix/radio-station#32]
When I check the "Encore Presentation" option on a show schedule entry and hit the "Update" button the "Encore" check box clears.  The schedule shows the time slot without the "Encore" notation, though items I have not updated still have theirs.  Don't know how long this has been going on. It has been a few months since the station last had a schedule change, but "Encore" worked then, and we did just install your latest update yesterday.

BTW, I'm delighted to see that someone with chops has taken up the Radio Station plugin.  One of the founders of the station set us up on it and is now gone, so I have been worried about depending for our public face on unsupported software.  -- Vic Tredwell, Station Manager, WBFY -- Community Radio in Belfast, Maine

**Comment by tonyzeoli** [comment]
Hey Vic,

An LPFM, WPVM 103.7 FM Asheville, NC, where I DJ and volunteer as webmaster was using the plugin, as well. When I saw that it hadn't been updated since 2015, I contacted Nikki Blight, the original author, and she was looking for someone to take it over.

I am not a developer myself, but I'm in product development, information architecture, and manage user experience design. But I've also been in and around radio and streaming Internet radio for most of my career. My interest found me eager to seek to take over the plugin. I'm grateful to @majick777 out of Australia for jumping in on the development side to see this through and get it updated to work with WP 5.2.2, as it was three versions behind.

This effort is still in its infancy and I'm seeking contributors, so if you know anyone interested in supporting the free version, that would be helpful. We hope to build a team of interested volunteers and then expand the offering to a PRO version.

I also control the Netmix.com domain name and am applying it to the effort, as well. Netmix was founded way back in 1995 and had a short run as a DJ culture startup, so I'd been looking for something today to attach the Netmix brand to. When this came up, it seems like a great opportunity.

In terms of the Encore Presentation feature, I'll be honest and say I'm not even sure what Encore Presentation does, lol. I know we have the Schedule Override, but I'll check into this and when @majick777 comes up for air on this, we'll work to resolve.

In the updates, I'm sure other things may have broken and I'm trying to catch up to QA on the entire plugin, so your eyes on this for us is super helpful.

**Comment by majick777** [comment]
@WBFYradio The checkbox saving was indeed broken so I have fixed that for the next version. Thanks for picking that. Was me being a bit over-zealous with security and sanitizing all the save values and I missed that one.

Seems all the encore checkbox does at the moment is display a line "encore airing" in the master program schedule. So to further improve this, I have also added "Encore Presentation" output to the display of the On Air and Upcoming widgets when this schedule override box is checked.

As far as I know in this context it means a repeat performance, rather than a new performance by the same person? Or is it both? I'm not sure how this has been used in the past, but I am curious to know what kind of scheduling this could apply to.
