### ISSUE TITLE
Open Shortcode in new tab & refresh shortcodes

### ISSUE THREAD

**Issue by Paul1173** [netmix/radio-station#326]
Is it possible to open a link in shortcode in a new tab? For example "current show" shortcode for example, we would like to open the link in a new tab so the audio player (Myradiostream) keeps running. Now, if we select the show link from the shortcode it is opened on the same tab so the audio stops.. 

2nd question, is it possible to refresh the shortcode in a code module? The "current show" and "upcoming-shows" do not refresh. With a standard refresh plugin  or code the whole page is refreshed and the same issue as above occurs, the music-player stops... So we would only want to refresh the 2 shortcodes in 2 seperate modules. (www.radiosd.nl)

Thank you!

**Comment by tonyzeoli** [comment]
@Paul1173 Answer to Question 2: In our forthcoming PRO version, we're bringing out a sticky footer player, so that you can replace your sidebar player with a footer player and no longer have to worry about the refresh knocking out the stream with the sidebar widget. The current show will display in the player. We can certainly work to display the upcoming show in the player, as well. I hadn't thought of that, but it's a good idea to do so. With widgets, whenever you refresh the page, it's going to reload everything anyway. There's no way that I know of to refresh the page and keep the widgets intact. That's why we're moving to a sticky footer player in PRO. I'd say give it two to four weeks from now. That's our target date for PRO. Get on the PRO waitlist at https://radiostation.pro.

I think the second question answered solves the first question too.

**Comment by majick777** [comment]
@Paul1173 For now you could filter the link using the `radio_station_current_show_title_display` filter to add a `target="_blank"` to the `<a>` tag. But it's not the best practice to be opening your links in new windows this way. I mean, there is probably going to be lots of other links on the page (navigation menus etc.) which will interrupt playback. This exactly why we are developing the persistent player for Pro.

Dynamic widget reloading will also be part of Pro, so that any of the Show widgets (Current Show/Upcoming Show/Current Playlist) will reload at the changeover time for a new Show. I believe another user tried this with a widget reload plugin that uses regular polling, but I'm not sure how that went.
