### ISSUE TITLE
Display of Widget Image and Text

### ISSUE THREAD

**Issue by scottdutton12** [netmix/radio-station#33]
Hi, is there any update on getting the image to show next to the text.

Im trying to replicate what is shown in the screenshot with the On Air thumbnail but Im getting the text showing under the image and further down.

Isle of Wight Radio's use of your plugin:

![on air thumb](https://user-images.githubusercontent.com/53665512/62417300-1eaa0100-b644-11e9-89a2-22e5b8cd03a6.PNG)

My current plugin on Moorlands Radio:

![neil freeman thumb](https://user-images.githubusercontent.com/53665512/62417299-1eaa0100-b644-11e9-8c31-ea85eebfce74.PNG)

I know a radio station that currently uses the Radio Station, https://iwradio.co.uk/ and their On Air DJ widget works a treat. You may be able to harvest some data from that site.

I want my widget to display like that on Isle of Wight Radio.

Any assistance would be a big help!

Thank you,

Scott

**Comment by tonyzeoli** [comment]
Hey Scott,

Thanks for submitting a feature request.

We actually just went through this here: https://github.com/netmix/radio-station/issues/30

We decided to stack the thumbnail on top of the text, because you cannot know what sidebar width someone is going to employ for their site and/or what size image they are going to use for the thumbnail. It could be different on twenty different sites.

You can modify with CSS. Visit the link I added here to the [Issue 30](https://github.com/netmix/radio-station/issues/30) where you will find the classes that you can manipulate to get the image to left align.

**Comment by majick777** [comment]
@scottdutton12 Thanks for the feedback! I had another look at this, and found a few things with the widget CSS that I've improved upon... bit of a rabbit hole. As mentioned the decision was made to give the title a new line and remove the explicit image sizing because sidebar widths may vary. Rather than forcing the image size to small and floated as it was, it is preferable to be full sidebar width and not floated by default, but can be made smaller and inline with the title if desired.

But what further distinction needed to be made (that @tonyzeoli hinted at #30) is that the full width image default should apply to the On Air widget but not to the Upcoming widget. The logic being the current playing show should display larger, but the upcoming shows as smaller in a list or the images crowd out the other show info. So these are the new widget defaults.

I don't like changing style defaults like this due to the risk of possibly ruining existing site styles as some seems to have happened a little, but in this case for the added improvement and flexibility something needed to happen. To fix and make up for the potential issues, I've improve this behaviour a lot more... Rather than have the need to manually add CSS styles to get this result, I've added two new options to each of those widgets (with the aforementioned sane defaults to fix the style changes) available from the Widgets page.

One to let you (optionally) set the show avatar image width (this can be different for each widget type.) And another to let you position the Show Title *relative to the avatar*... whether below or to the right of the avatar - but also above or left of it - which were missing options here that some may prefer (ie. for having the show title up top or for righthand sidebars.) Existing sites do not need to set these options, they will just take up the defaults, but they are now there if wanted or needed.

I have put the cleaned up and improved widgets and CSS in the next version to be released (2.2.4), but you can download the development copy here from Github if you want to implement this before then.

**Comment by scottdutton12** [comment]
@majick777 I can't thank you enough for taking a look into this! If this works I will be forever greatful!

May I ask where I can download the development copy from, do you have a link?

Thank you so much!

**Comment by majick777** [comment]
@scottdutton12 No problem, our aim is to keep on top of bugs like this so we can move on and start adding further enhancements and features. There is a Patreon account up at https://www.patreon.com/radiostation if you would like to show support, hopefully we can build enough subscribers to fund making this better and better. :-)

From the main Github repository page for the project, https://github.com/netmix/radio-station/
you can scroll down and on the right the Clone/Download green button and download the latest zip, 2.2.4 will be up on WordPress SVN repository later today also.

**Comment by tonyzeoli** [comment]
As @majick777 instructed, you can download the development version using
the link he provided. But, I'll be pushing this after testing. I'm testing
in the morning eastern standard time. You should see an update in your
WordPress Dashboard most likely before 1 pm EST, but if you take the
development version and rename the zip from "radio-station-master" to
"radio-station," then upload via WordPress Plugin page or unpack and upload
via FTP, you'll have the latest, but not fully tested yet.

**Comment by tonyzeoli** [comment]
I just pushed 2.2.4 with the new layout manager for the sidebar widgets for Show / DJ On Air and Upcoming Show /DJ On Air. You'll find that @majick777 did a fantastic job of giving you a setting to move your Show Title above, below, or left/right align of the thumbnail. You can also increase/decrease the size of the thumbnail, or leave as default.
