### ISSUE TITLE
[Schedule] Displaying different Show shift to Show page

### ISSUE THREAD

**Issue by XLRradio** [netmix/radio-station#330]
**Describe the bug**
Well as the title says the Schedule Table is showing different times to what is set in the Show Page.

note the show goes over the midnight hour (10pm-1am)

![image](https://user-images.githubusercontent.com/63446711/112761198-0e515180-8ff2-11eb-9ebd-a17667692928.png)

![image](https://user-images.githubusercontent.com/63446711/112761175-e366fd80-8ff1-11eb-9986-2f200593304c.png)

Thats how its set up but on the schedule on the website tells a different story

![image](https://user-images.githubusercontent.com/63446711/112761227-3e98f000-8ff2-11eb-90de-dfb2fd37d582.png)

even the next show starts at 2am when its set to 1am
![image](https://user-images.githubusercontent.com/63446711/112761284-7c961400-8ff2-11eb-9468-3d891eca3234.png)
website is this
![image](https://user-images.githubusercontent.com/63446711/112761253-5ec8af00-8ff2-11eb-88ee-88bee9eb444e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Edge
 - Version 89.0.774.63 (Official build) (64-bit)

**Comment by XLRradio** [comment]
@majick777

**Comment by majick777** [comment]
@XLRradio Have not been able to reproduce this yet from the example given. Can I double check which version of the plugin you are experiencing this with? So I can recheck whether this is a version-specific bug?
And whether it persists when you use the "Save Shifts" button and/or the Show "Update" button? It seems odd that the displayed schedule it exactly one hour out from the exact shifts.
Or if you can provide me with a schedule URL I can try to check the debug information to see what is happening on the site itself rather than trying to recreate the problem locally.

**Comment by majick777** [comment]
@XLRradio Haven't got any further from you on this, seems like something specific you are experiencing... Can you test this out with the latest development version and see if the problem still persists?

**Comment by tonyzeoli** [comment]
@majick777 @XLRradio The last comment on this post was on May 29th and the issue could not be reproduced. I need to clear our backlog, so am closing this issue. If there's an additional need, feel free to re-open a new issue.
