### ISSUE TITLE
[MetaRadio Integration] Widget CSS classes

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#335]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
In the settings of the current show and upcoming show widgets I would like the ability to add a css class to the widget

**Describe alternatives you've considered**
None?

**Additional context**
I would like this as I want to use metaradio to hide the who is live widget when a song is playing to allow the presenter image and name to be replaced with the song artwork and name (again by metaradio) Meta Radio provides the CSS classes already but I can't insert them into the Radio Station Widgets

**Comment by tonyzeoli** [comment]
@kairandles Okay, let's see what we can do hear.

BTW, we are talking to the folks that make MetaRadio about an API integration with their software to be able to pull from MetaRadio. Right now, we're push only, but in the coming weeks, we'll be looking at supporting MetaRadio into Radio with Station.

If @majick777 adds these classes, you'll need to pull the development version until we finalize the next release in order to use them.

I've assigned this ticket and we'll see what we can do.

**Comment by kairandles** [comment]
Sure thank you! And that sounds amazing!!

Something I did notice @majick777 is that elements that use the class also need an attribute like data-stationid="2" so for example <div class="row metaradio-hide-now-empty
" data-stationid="2" >

Any ideas?

**Comment by kairandles** [comment]
Hey just so you know I have resolved this by putting converting to shortcode and then putting it inside a div container with the properties above.

Feel free to still put the custom css classes in however I don't specifically need this feature anymore :)

**Comment by tonyzeoli** [comment]
Okay, it may make sense to do that. We'll chat about it internally. I'll keep this open until @majick777 gets through here to pick it up. He's busy working on PRO, so we are trying not to distract with minor issues until that is launched in about two weeks.

**Comment by majick777** [comment]
@kairandles Is there documentation you can point to on MetaRadio that describes what classes are needed for this?
Haven't had time to look further into the MetaRadio integration myself yet.

In the meanwhile, it should be easy enough to add new divs manually via the custom HTML filters for the widgets..?
Or are you talking about adding the MetaRadio classes to the existing widget elements? As this might be fairly easy to do with jQuery also, or we possibly we can add some more filters for those specifically.

**Comment by kairandles** [comment]
@majick777 I'm thinking more how other plugins have the add CSS classes feature? See screenshot 

![IMG_20210421_044148.jpg](https://user-images.githubusercontent.com/77554122/115493616-f620cb00-a25b-11eb-8756-b794b2845df4.jpg)

**Comment by majick777** [comment]
@kairandles Okay hmmm, but what element(s) would the specified classes be added to? 
Are you meaning for the widget container or other HTML elements internal to it?

**Comment by kairandles** [comment]
@majick777 

'm not too sure, as I say I don't personally need this feature any more I simply put the widget as shortcode and put it inside a div container.

For reference I wanted the header widget to change dynamically with what song is playing and who is live this widget is used to show the presenter live while they are talking but switch to the song they are playing if a song is playing see video example [https://photos.app.goo.gl/a7dHGkuRUNnzcif38](https://photos.app.goo.gl/a7dHGkuRUNnzcif38)

So I needed it for the full widget but it could be useful to be able to add classes to more internal elements however not sure how that would be achieved?!

**Comment by tonyzeoli** [comment]
@kairandles In PRO, widgets are now dynamic, so they will display changes dynamically. Because you're the only one to seemingly ask for and need this feature, but you've already solved it, I'm going to close it now. Also, we are now displaying song information in PRO that changes dynamically in the audio player bar, but it has to come from a shoutcast or icecast feed.

**Comment by tonyzeoli** [comment]
Closing this.
