### ISSUE TITLE
[Tabbed Schedule View] Weird issue - Saturday flips darker than rest of tabbed schedule

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#339]
**Describe the bug**

Not sure what this is, but when you click Saturday in the tabbed view, it displays the thumbnail darker than the other views. Not sure if it's duplicating Friday or if there's some other issue.

**To Reproduce**
1. Go to tabbed view
2. Click on Friday, then Saturday
3. Notice the differentiation in color for the image

**Expected behavior**

Should be consistent.

**Screenshots**

https://www.loom.com/share/12cc0c79d8904b69a49a947a5a017557

**Desktop (please complete the following information):**
 - OS: 10.5.7
 - Browser Chrome
 - Version most recent

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
This is due to the reduced opacity on all Shows before the current show from #283
Although, it should be noted that I recently changed the code so that it is before the current *time* rather than current *show*, because when there is no actual current show, previous shows should still have the reduced opacity.

I guess the oddity here is that you are viewing Saturday on Saturday everything else appears with reduced opacity... I don't know if there is anything further we can do to make it clearer to the user why the difference in display, especially when there is no current show, but this is what we had decided upon.
