### ISSUE TITLE
Multiple Station Support

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#350]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Hey, this is a massive feature so I'm not sure of the scope of this (so may have to be something for PRO or something) but here goes please let me know your thoughts...

The ability to have multiple stations on the same WordPress installation. So each of the widgets, shortcodes etc would have to choose what station they refer to (as well as if it's not selected resorting to a default station to not mess up other installations)

We have a few stations that are 'sub stations' so all the same brand however for some songs or presenter links etc they all localize to say London, New York, etc

**Describe alternatives you've considered**
Using WordPress multisite and installing on mydomain.com/digital and mydomain.com/london etc however I simply want all the same content across the sites so the finicky syncing plugins etc aren't ideal

**Additional context**
As I say this would be no easy feat I don't think however it's an idea and something that would make my life easier but I'm not sure if there is a demand for it other than me?

**Comment by tonyzeoli** [comment]
@kairandles Definitely something for PRO, no question. This is pretty massive and would probably be something we do in Q4 this year once we get PRO out in the next few weeks. We're almost done with our PRO first version, which will be 2.4.0 in terms of release version number. It's got:

Sticky Footer Player
Episodes Post Type
Show Host/Producer Pages
Grid and Calendar View
Multi View Switching
Time Zone Switching
YAML Import/Export

In 2.4.1, we'll be introducing Segments and a tools to tag segments from Episodes. We'll probably work with Blrbrry for podcasting and feature their system for integration with Radio Station.

In 2.4.2, we're probably going to add monthly, bi-monthly, or every third week options for the scheduling system, so that if a show doesn't happen weekly but say bi-monnthly, it can have it's own page.

Then, we can get to a multisite sort of thing. I've already talked to Tony about multiple schedules in a single site and widgets to be set to whatever schedule they need to be set to.

For something like multisite, that would be us having to go to a software as a service model and using a plugin that can set the calendar shortcodes into each site individually across the multiste and you'd manage the entire calendar in a website you log into. It's not advisable to set some kind of admin up on the primary site that runs all sites in the network unless it's added to the network admin panel, I guess. But, at that point, I'd just think we'd need a SaaS admin and change the way we do things completely.

**Comment by kairandles** [comment]
Sure, exactly what I thought you would say. That works great for me. I've got the solution mentioned at the moment but would be great to chat further down the line when pro is live! - Very excited for it!

P.S will there be a free trial or something? Need to come up with a way to get the funds for it lol and I think demoing would be a good start!

**Comment by tonyzeoli** [comment]
@kairandles There is a free trial now. 7 days, but need to set a credit card to use it. There's a 30 day refund guarantee, as well.

**Comment by tonyzeoli** [comment]
Going to close this issue now, because we're going to add multi-schedule views in PRO.
