### ISSUE TITLE
[ Deployment ] v.2.4.0.2

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#367]
**Is your developer task related to a problem or a requirement? Please describe.**

Deploy version 2.4.0.2 to SVN repo at WordPress.org

**Describe the solution you'd like**

Check version numbers in:

- radiostation.php, readme.txt
- readme.md
- readme.txt

Check the stable version number.
Check the tested up to version number.

Make sure all changes are added to the changelog.

**Describe alternatives you've considered**

**Additional context**

**Comment by tonyzeoli** [comment]
@majick777 pleae update the stable tag in the readme to 2.4.0.2

**Comment by tonyzeoli** [comment]
This has been committed but am not closing until the stable tag is updated and pushed to Master.

**Comment by majick777** [comment]
Okay have bumped that in the readme.txt on Github now and did a hotfix on the master branch.
Argh still don't know how a round of readme updates disappeared.

I checked the SVN via https://plugins.svn.wordpress.org/radio-station/trunk/
and the trunk readme.txt still has 2.4.0.1 in the Stable tag (and the 2.4.0.1 tagged directory doesn't exist, so that is a problem) - so that single file needs updating.
and there is no tagged version at /tags/2.4.0.2 - so the new version (master branch) needs to be uploaded to to match.

**Comment by tonyzeoli** [comment]
Yup, will do.


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  ***@***.***
***@***.***>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
Clubhouse @tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
[image: App Social Buttons Image]
<https://facebook.com/digitalstrategyworks>  [image: App Social Buttons
Image] <http://dswks>  [image: App Social Buttons Image]
<https://linkedin.com/in/+tonyzeoli>  [image: App Social Buttons Image]
<https://www.youtube.com/+digitalstrategyworks>
Schedule a Call [image: arrow] <https://calendly.com/tonyzeoli>
‌

**Comment by tonyzeoli** [comment]
Okay, this is committed and completed.
