### ISSUE TITLE
 possibility to change the player "sonaar player"

### ISSUE THREAD

**Issue by BenjaminITTF** [netmix/radio-station#369]
It will be possible to add the player sonaar player?

**Comment by tonyzeoli** [comment]
If you're talking about the Sonaar player here: https://sonaar.io/free-mp3-music-player-plugin-for-wordpress/?utm_source=Sonaar+Music+Free+Plugin&utm_medium=plugin

We cannot included someone else's player in our free plugin, especially a PRO player like Sonaar is. However, we have created a PRO version of our plugin, [Radio Station PRO,](https://radiostation.pro) which includes a persistent audio player similar to Sonaar. It doesn't have all the specific feature of Sonaar yet, but we are working gon those options for the future.

I'm sure you can purchase Sonaar yourself and try it with Radio Station, the free version, but for the future we are building out a similar player and you'll need to upgrade to PRO for that experience.

**Comment by tonyzeoli** [comment]
One more thing. Sonaar is a "jukebox" player - you have to upload your own MP3s. It doesn't play a live stream...at least I didn't see that on their website. But correct me if I'm wrong.

**Comment by majick777** [comment]
@BenjaminITTF We are focussing our player efforts on supporting audio streams, rather than file playlists. There are a number of players out there such as Sonaar which already have extensive playlist support. 

While we will be introducing further file playing and playlist support into the Pro version of the player for use with Episodes, this will be focussed on the on-demand aspect for recording past Shows, rather than a jukebox style player for individual tracks.

**Comment by majick777** [comment]
@BenjaminITTF Your images are not coming through. Please recheck the ticket to make sure they are there after commenting. Can you start a new issue regarding the Genre Highlighting problem, including the version of the plugin you are using and any javascript errors from your browser's Developer Console.
