### ISSUE TITLE
Need Help Not playing 

### ISSUE THREAD

**Issue by binura1** [netmix/radio-station#410]
hi I install plugin. time table is working perfect . but its not playing.
I try to fix Permalink Settings but didn't work .I'm new to WordPress I don't know weather I do it correct.
can some one help me to fix this.
after play button click screen lock like this
https://postimg.cc/MMprd5t7

this is how my permalinks look like WordPress
https://postimg.cc/30yfHwsW

this is radio timetable

https://postimg.cc/rzbYNS44

this is page button look like.

https://postimg.cc/Jtt2XTsm

thank you

**Comment by tonyzeoli** [comment]
Please type the URL for the website so we can take a look.

When you say it is "not playing," I don't understand what is not playing?

Playlists do not play back audio. They are just text playlists.

If you have a stream you ate trying to use, it must start with https amd not http. Browsers will not play back http streams. They must be secure.

**Comment by tonyzeoli** [comment]
@binura1 in the first screenshot, it's just a white screen at a URL. Not sure what you're asking us to look at.

**Comment by majick777** [comment]
@binura1 Github issues are for bug reports and feature tracking, please submit any plugin support requests via the WP Support Forum: https://wordpress.org/support/plugin/radio-station/

If you can include a more detailed description there of what you have tried and what is not working for you, and include any relevant page URLs there it would be appreciated. The screenshots you've provided don't give us anything to go on. 

If it does turn out to be a bug then we can open a ticket back here on Github for it, otherwise if it turns out to be just pertaining to you, we can solve it via the support forum there.
