### ISSUE TITLE
[Current Shows] Shortcodes vs widgets, caching and auto-reload

### ISSUE THREAD

**Issue by jerrell-rebel** [netmix/radio-station#428]
**Describe the bug**
Good day!

First of all, great plugin!

I just seem to be having an issue with the current show shortcode.

The next show does not seem to load or show on the front-end unless you refresh the cache on the backend. I have read and seen similar issues but they seem to use the widget not the shortcode.

Should you need more information please do let me know. Thanks!

**Comment by tonyzeoli** [comment]
@majick777 please check this, thanks.

**Comment by majick777** [comment]
@jerrel-rebel 
The widgets are basically control panels for the shortcodes - widgets just call the shortcodes with the specified options.
So you can have AJAX loading set on the widget or the shortcode (the default is set in the plugin Settings) and this will bypass a page cache to ensure the Current Show display output  is loaded via javascript and an AJAX request.

However, if you are talking about automatic reloading at Show changeover, this is something we have included in the Pro version of the plugin (https://radiostation.pro)  The other discussions you have seen may be around the other possibility for widget reloading using a cyclic widget reloader plugin I believe (that is to say, it reloads at a specified interval rather than at the exact time.) 

I'm not sure if you could get that to work directly with a shortcode or not, but you could try a Widget-Shortcode plugin, that is one that creates a Widget Area that you can call via shortcode, then drop the Current Show widget in the Widget Area, use the shortcode to display that widget area instead of the current show shortcode, then the interval widget reloader might work to automatically reload that area.

Again, the feature is already in Pro, so that'd be the fastest and simplest way to achieve this, but if you are looking for a more complex but free way to achieve the same that's all I can really suggest.
