### ISSUE TITLE
Player icons are backwards

### ISSUE THREAD

**Issue by RadHausStudio** [netmix/radio-station#432]
The player icons seem to be backwards. When it's playing, the icon should be the pause button, and when it's paused, the icon should be the play button. Better yet, there should be three icons: play, pause, and stop, perhaps with the active state highlighted with a different color border.

![player icons are backwards](https://user-images.githubusercontent.com/609208/194152460-c79ae454-537b-4afb-bb2a-316be8c1c618.png)

**Comment by majick777** [comment]
@RadHausStudio Thanks for noticing, there was a problem in the stylesheet for the updated player graphics, so that play and pause were not showing properly. It has been updated in the development version for the next release.

We decided for the stream player it just doesn't make sense to have a "stop" button. In the future we'll add better file playing support, and file playlist support...  in those cases, there will be a stop button, as well as previous/next track, and a progress bar etc.

**Comment by RadHausStudio** [comment]
I worked up a custom icon set, and swapped the play and pause buttons, but now it's the pause button that appears when the page first loads. What I'm hoping for is

- on initial page load, play button appears
- when in play, pause button should appear
- when paused, play button should appear

Or, a row of three (play, pause, stop), where the active button is highlighted. The :hover state works, and :active works for the click itself, but the pseudo tag for :visited didn't seem to affect the state, so I am having trouble solving this with CSS. If you have any other suggestions, please let me know!

Also, for streaming radio, does the pause actually function as pause, or stop? In other words, does the existing cache simply get picked up again from where the listener stopped, or does it catch up to the current stream when you restart it after pause? It seems to get confused when I stop and start it.

**Comment by majick777** [comment]
@RadHausStudio Okay, but if you swapped them, and I swapped them, then it's going to be back around the wrong way again? 

```
- on initial page load, play button appears
- on hover, before player is activated, play button should be highlighted
- when in play, pause button should appear
- when in play, on hover, pause button should be highlighted
- when paused, play button should appear
- when paused, on hover, play button should be highlighted
```

As you've described it, this is the behaviour that already exists (before and after I mucked the stylesheet in that development version.) The highlight on hover is a change in the button opacity regardless of the state. 

What isn't obvious is that different player events trigger the adding of different classes to the player container (`radio-container`) - so those can be targeted if you want to customize things a bit further. Also, when a stream is loading it glows blue and when playing it glows green. If the stream fails to load the button changes to red. These are CSS animations triggered by the classes mentioned, so they can be overridden too if you want a different animation style.

For example, if you want to accentuate the highlight of the difference in opacity when the player is loaded (whether paused or playing) you can do say:
`.radio-container.loaded .rp-play-pause-button {opacity: 0.7;}
.radio-container.loaded .rp-play-pause-button:hover {opacity: 1;}`
Because on hover the opacity is normally 1 (no transparency / "highlight") But the second rule is needed to override the change in the default of the first (from non-hover opacity of 0.9)

**Comment by RadHausStudio** [comment]
Oh, that's helpful; thank you!
