### ISSUE TITLE
Can't uninstall since upgrading to Wordpress 6

### ISSUE THREAD

**Issue by semipelagian** [netmix/radio-station#436]
I've been getting JSON errors when trying to schedule future posts on my website. This may be nothing to do with Radio Station but I've been trying to deactivate plugins on the Word Press Plug Ins page to see which one is causing the problem. When clicking the option to 'Deactivate' Radio Station I would expect it to deactivate and then change this option from 'Deactivate' to 'Activate'.

Instead, when I try to deactivate Radio Station in the Plug Ins page I get the white screen with the message "There has been a critical error on this website. Please check your site admin email inbox for instructions." As it happens I don't get an email and I can easily go back into the Wordpress Dashboard by using the back button, where it behaves normally. So it doesn't completely crash. However, being unable to deactivate a plugin is quite worrying. 

**Desktop (please complete the following information):**
 - OS: OS X and Windows 10 
 - Browser -Chrome 
 - Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by tonyzeoli** [comment]
There are two other ways to deactivate a plugin. If your host allows for WP CLI via connecting through SSH, there is a simple command to deactivate a plugin.

I personally didn't use WP CLI until a few weeks ago and now that I have it it's a great tool. You don't need to be a d enveloper, just understand how to login via SSH to your server then navigate to the WordPress folder and Google the commands you need, which are all in the WO CLI docs. Just being able to use WP CLI to print a plugin list to the screen to see what's active or not active and needs an update is useful. And, having the ability to activate or deactivate plugins this way is useful too. It's relatively easy once you learn how to login, how to navigate to a folder using "cd folder-name" and backing out. These are the simplest of ssh commands.

Alternatively, you can login via FTP or SFTP depending on what your host offers and rename the plugin folder by appending a "*" or something like "radiostation(disabled)" so that, at the very least, you can uninstall the plugin.

We have tested against php 8 and have made sure to update the plugin for those using 8, but check that you're on 8. If you are, learn from your host how to roll back to 7.4 and see if that helps.

Who are you using as your hosting provider?

As you can see at demo.radiostation.pro, we are running the latest version with the upgrade to WP 6.1.1. So there is some conflict with your theme or another plugin, I surmise.

You can try to change your theme to a base WordPress theme also to see if it's the theme you're using causing the issue. 

Let us know what you find out and we'll do our best to help.

**Comment by semipelagian** [comment]
Thanks Tony,

That’s really helpful. 

We’re on PHP 8 and the hoster is Dreamhost. We use the Astra theme. 

I’m a bit reluctant to swap the theme, even temporarily, as there are quite a few unique formatting options for Astra that don’t seem to go back to normal when it is reinstated. 

The problem we have is quite specific and only occurs when we schedule a post. We get an error message and the post appears that it hasn’t saved. Often it has saved and WP has ignored the scheduled date and already published it. We have a workaround. If we save it as a draft and then schedule it using the Quick Edit WP feature, it works fine. 

Anyway, like I said in the original message, that may be nothing to do with Radio Station so none of that is your concern. I just wondered whether the lack of ability to deactivate it was a related clue. Probably not.

I’ve not used SSH before so it’s a bit on the edge of my experience although it’s probably simpler than I imagine if Dreamhost support it. Changing names via SFTP sounds relatively straight forward. 

Probably the best thing for me to do is to disable each of the other remaining Plugin’s when I get a moment (I got about halfway down our list) and check if that makes a difference. Then if that doesn’t bring joy, try to manually disable Radio Station.

Anyway, thanks again. If I come up with anything else that might be related to Radio Station, I will let you know.

Kind regards,




Steve Perry
***@***.***

**Comment by tonyzeoli** [comment]
Sure, no problem.

You should also maybe try to install the Health Check and Troubleshooting
plugin from WordPress, which will help you keep your site live
while spoofing that all plugins are enabled, but let you disable them in
the background to test.

And, yes, that's why it's always good to have a DEV, STAGING, and LIVE
environment. You should check into whether your hosting provides that level
of functionality, so you can always test your theories/changes
before you push live.

i'm going to guess that it's a php 8 issue. Many plugins haven't factored
for php 8, which is very, very strict. So, I would try to set php to 7.4.
It's just a selection in your control panel. That may be the issue.

**Comment by majick777** [comment]
@semipelagian Do you have Pro installed as well? We recently came across a similar issue when Pro was installed and active. If this is the case if you deactivate Pro first then the free version, it should be fine. It may be something else but I thought I'd mention it.

**Comment by semipelagian** [comment]
No, we're just on the free version at the moment.

Steve

**Comment by tonyzeoli** [comment]
@semipelagian are you still having this issue?

**Comment by semipelagian** [comment]
Hi Tony,

Thanks for asking. 

Yes, I’m still having it. Radio Station still won't deactivate. I get the same critical error message when I try. However, I haven’t looked into manually uninstalling it yet. As you may remember from my original message, I don’t really want to uninstall it, particularly, I just thought it might be a clue to the real problem I have which is posts not scheduling properly (I get the error message "Scheduling failed. The response is not a valid JSON response.”)

I tried disabling all the other Plug-ins, on at a time. No joy with that either. 

I think you suggested going back to PHP 7.0 but I haven’t looked into that yet as I’ve not had the time since then. In fact the only thing I’ve had the time to do is just keep updating all my plugins in hope that one of them might fix it. However, it is still an issue at the time of writing this. 

Steve

**Comment by semipelagian** [comment]
Hi again,

As you reminded me I looked in to changing the PHP on Dreamhost whilst I was waiting for something else to process. Turns out it’s really easy so didn’t take long to ‘downgrade’ from 8.0 back to 7.4.

The interesting this is that I don’t get the ‘Critical’ error when deactivating Radio Station in 7.4. So I managed to deactivate it successfully and test and it definitely isn’t Radio Station causing the problem. 

The bad news is that I still get the JSON error when scheduling posts. However, that isn’t related to radio station. Interesting that I can’t install Radio Station under PHP 8 though.

Thanks again for the help.

Steve

**Comment by majick777** [comment]
@semipelagian I strongly recommend testing the latest development version to see if that fixes the problem. 
I did make some changes which may be related to this issue. 
https://radiostation.pro/docs/faq/#how-do-i-install-the-latest-development-version-for-testing

Also worth testing in combination with the Beta Pro version (see instructions via the same link.) 

We are very close to releasing both of these new versions, as they are major updates so have taken quite some time.

**Comment by majick777** [comment]
@semipelagian Closing out this issue as resolved in release version.
