### ISSUE TITLE
Help with rs-custom.css

### ISSUE THREAD

**Issue by thorssig** [netmix/radio-station#463]
Hi,
I have been messing with css setting on the radio-player plugin and have gotten it pretty much how I like it.

![spilari1](https://github.com/netmix/radio-station/assets/133007747/8d8c7cf3-cc82-43a7-b5c0-78606168831a)

So far I've been using Appearance->Customize->Additional CSS to experiment and have read about putting a rs-custom.css in the css folder but when I try to move the modification nothing happens.

Also when I narrow the browser enough the player shows 2 widths, plus some min-width definition, which I don't see defined anywhere. Perhaps it has partly switched to some other css profile for mobiles?

![spilari2](https://github.com/netmix/radio-station/assets/133007747/2fbfcff7-5fd7-458c-9238-d439bf0f5310)

This bug applies to Chrome, Edge and Firefox...

Any ideas?
Þorsteinn Sigurðsson

**Comment by majick777** [comment]
@thorssig You can put the `rs-custom.css` in your child theme directory in a `/css` or `/style` subdirectory, so that it persists between parent theme updates.
For the width issue can you provide an URL so I can take a look at what is happening,

**Comment by thorssig** [comment]
Our dev server is at: https://wordpress-1000093-3520884.cloudwaysapps.com/
I've been messing around with it and found that it has to do with
the radio-station-player-bar and specifically player-bar-arrow
and player-bar-label. I can hide the arrow and the label but still haven't
been able to fix that different behaviour between  radio-station-player-bar
and  radio-player-shortcode. Guess I'll have to go over them and mirror the
css attributes from the player in the player bar.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by majick777** [comment]
@thorssig In your custom CSS, there seems to be a mangled rule at `#radio-station-player-bar .radio-container` so check that. There are missing brackets and other ignored rules (looks like a misplaced copy and paste there.)

But also, if you set that container to a height of 33px instead of 30px it might fix the issue. That difference might seem trivial, but the responsiveness javascript uses a trick of detecting when the content splits into another line by comparing section heights. Right now the responsive sections are not being triggered properly because the container height is just a little too small.

**Comment by majick777** [comment]
@thorssig Closing this issue as resolved. Any further problems with this and we can re-open it.
