### ISSUE TITLE
Translation does not seem to work?

### ISSUE THREAD

**Issue by EastOne57** [netmix/radio-station#465]
I have a site which should be all dutch language.
All settings are set fopr ducth, WP main language and RSpro all set to 'Nederlands'.
But non of the tranlated strings shows up.
I checked the WP translation project for this plugin, but it doesn;t seem to work..
https://translate.wordpress.org/projects/wp-plugins/radio-station/stable/nl/default/
Actually almost all is done...

https://rcantwerpen.be/show/de-praattafel/
RS/RSpro; current version.s

This is a big issue here so I hope there is an easy fix?

MTA, East1

**Comment by tonyzeoli** [comment]
We have another user just the other day who is using Dutch and reported no issue with the language displaying, but needed to update strings, which is why you're seeing the language complete.

I'll assign this to our lead developer, Tony Hayes, yo pick up and see if he can assist.

**Comment by tonyzeoli** [comment]
Okay, we figured out what's happening. According to the WordPress translations handbook, translations are not Automattic until they are 90% complete. We've taken the latest updates to the .pot file and included them in the development release here on git, so take the latest development version which includes the updated .pot file and that should work.

**Comment by EastOne57** [comment]
Ok!

Now if want to add more translations, how would we go about that?

MMMTA!, Again...

Grts, Istvan

Istvan Leel-Össy
*Theatrical engineer. sound-light-video-radio-podcast*
*DB Radio Centraal vzw*



*+32 (484) 731.357 gsmemail: ***@***.***
***@***.***>Kardinaal Mercierlei 33/1*
*2600 Berchem*

*http://istvanleelossy.com <http://istvanleelossy.com>*

*"I'm an Engineer Because Miracle Worker Is Not An Official Job Title"*


Op zo 30 jul 2023 om 20:02 schreef Tony Zeoli ***@***.***>:

**Comment by tonyzeoli** [comment]
Radio Station is not responsible for the adoption of translations. Anyone who needs translations must work with the WordPress translation system to improve the translation strings available to the plugin. The best we can do is take the most recent translations available and add them to the folder in the plugin or you can do the same on your side and keep updating the .pot files for the required translation, as you see necessary. Translations are a volunteer effort and those who use the plugin (or any plugin, for that matter) and need translation in the preferred language must keep abreast of the requirements in your environment and workflow. It's something you have to take the time to learn and improve on yourselves. Now, that being said, I have not yet assessed if the strings in PRO actually show up for Episodes, in the translation system as I'm not clear myself on whether only strings in free appear and we have to somehow include PRO because we do not submit PRO to the WordPress repo. That's something we need to do a better job of understanding and I'll take a look at how that works and see if it's already there or needs to be added somehow that we're not sure of.

**Comment by EastOne57** [comment]
Ok, thanks for the clarification.

Grt, Istvan (on mobile somewhere)

Op ma 31 jul. 2023 02:22 schreef Tony Zeoli ***@***.***>:

**Comment by majick777** [comment]
@EastOne57 Actually the WordPress translate system (Glotpress) was set up specifically so that anyone can contribute translation suggestions. These are then approved by project editors (or failing that, existing translation editors for that language.)

The translation project for dutch is at:
https://translate.wordpress.org/projects/wp-plugins/radio-station/stable/nl/default/

If you are logged in to WordPress.Org, you can simply double click on any untranslated text there to make a suggestion as to the correct translation. We can welcome any contributions this way. 

You will also notice a link on the translation project page that you can apply to become a project editor (ie. for the dutch language translation for this plugin):
https://make.wordpress.org/polyglots/handbook/plugin-theme-authors-guide/pte-request/

@tonyzeoli We should probably do a better write up of this information and add/update the FAQ.

**Comment by EastOne57** [comment]
Hi,

Tnx 4 the info.
I actually did already do  bunch of them.
Only now they are implemented by Tony with a temp fix...



Grts, Istvan

Istvan Leel-Össy

sound-light-video-action!
Radiomaker - Podcaster

+32 (484) 731.357 gsm
email: ***@***.***

Kardinaal Mercierlei 33/1
2600 Berchem

http://istvanleelossy.com
http://praattafel.be

"I'm an Engineer Because Miracle Worker Is Not An Official Job Title"

Op ma 31 jul. 2023 10:27 schreef majick777 ***@***.***>:

**Comment by tonyzeoli** [comment]
I did confirm with @majick777 that PRO strings are included in the translation system along with free strings, so you'll be able to update all free and pro strings at once and don't have to be concerned if they are separated.
