### ISSUE TITLE
[ API ] Displaying incorrect time for the current_show

### ISSUE THREAD

**Issue by bmgage1993** [netmix/radio-station#486]
**Describe the bug**
I am developing a mobile app for my radio station that uses this plugin's API. When I navigate to the API /wp-json/radio/station, it displays current_show and it is the correct show, but the start and end time are incorrect. However, further down in the json, the schedule is correct. 

**Screenshots**
<img width="1512" alt="image" src="https://github.com/netmix/radio-station/assets/115111269/ee545b94-0efc-472f-9fb2-7081808d5180">

<img width="1512" alt="image" src="https://github.com/netmix/radio-station/assets/115111269/11a2c220-5e74-48f5-b430-327f4921a290">

**Comment by ollydowning** [comment]
+1 for this, also seeing current_show and next_show returning the same values.

**Comment by tonyzeoli** [comment]
@bmgage1993 @ollydowning Thanks for reporting this.

First, @bmgage1993 , awesome that you're building a mobile app from our API. I'd love to interview you for our blog after you finish it so we can feature what's possible with the API. Hopefully, we'll get to a pull API in the future so that it's a two way street.

@ollydowning Thanks for chiming in.

@majick777 will take a look at this and push a fix as a dev release candidate for you to take and see if his fix solve the issue.

**Comment by majick777** [comment]
@bmgage1993 @ollydowning 
I've just added a patch for this, seems I was overzealous in using a time conversion function in 2.5.6 and it was double-converting the timezones in the broadcast data, making the current_show/next_show times wrong.

Check out the latest via develop branch (or 2.5.9 release):
https://github.com/netmix/radio-station/tree/develop
https://github.com/netmix/radio-station/releases/tag/2.5.9

**Comment by tonyzeoli** [comment]
@bmgage1993 A patch has been issued by @majick777 for this issue. Closing this ticket.
