### ISSUE TITLE
Tabs shift to second line

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#55]
**Describe the bug**
When viewing the Tab version on the demo site, the tabs shift to a second line. I can't ascertain whether this is because of the content width or not, given the sidebar on this page.

<img width="1552" alt="Screen Shot 2019-09-13 at 10 44 07 AM" src="https://user-images.githubusercontent.com/4053819/64871599-8bd18e80-d613-11e9-8a59-1211f6d1e30a.png">

**To Reproduce**
1. Go to https://netmix.co/radio-station-demo/tabbed-schedule/
2. View tabs in page with sidebar

**Expected behavior**
Tabs should be responsive to the page width to stack horizontally on one line.
In mobile, tags should reduce down to fit iPhone 5 screens and equivalent, as well.

**Screenshots**
Attached screenshot above.

**Desktop (please complete the following information):**
Chrome for Mac (latest version)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by majick777** [comment]
This is partly intentional so that it is responsive, that is to say so that the list items *can* wrap when there is insufficient width for the full display (whereas a lot of other element formats don't handle this so well.) The original tutorial had a fixed 500px width total which seemed too small and cramped the tabs so I added some margins to space them out... and it is these margins that are pushing the list into two lines. The only way I can see around this is to add some CSS media queries to change the list item margin sizes for different screen widths.

**Comment by tonyzeoli** [comment]
@majick777 We might be able to assign media queries to @jmarx as it's a small change to add media queries and I think he may be able to help here while you focus on other priorities.

I see your point about the wrapping for responsive, but shouldn't the tabs not have white space between them? If someone were to natively implement this with no modifications, it would just look bad on all sites displaying tabs with that white space, like it wasn't finished or something. Do you agree? Disagree? Is there something I'm not taking into consideration? Let me know, as my first perception was didn't look like something that someone might be comfortable implmenting on their own site when the tabs have that whitespace between them.

**Comment by tonyzeoli** [comment]
@majick777 P.S. And, given this is on the radio station website demo page, it doesn't look like a good model if someone where to want to review and implement. They may look at the demo and say, "so what am I supposed to do now with the tabs shifting to a second line and the whitespace between the tabs?" Especially if they are like me, not a developer, but know how to implement the shortcode.

**Comment by majick777** [comment]
Seems like the styles were simply out, I changed float:left, display: block to simply display:inline-block for that tabs and they seem to collapse gracefully. They don't have actually margins set on them so this behaviour was probably due to that too. I've updated this for 2.3.0, we can double check in the testing on the demo site and reopen if needed.

**Comment by majick777** [comment]
Actually turns out the margin was being overridden by the theme here, which pointed to the fact that the tabbed schedule styles did not have enough specificity in them to create a standalone layout... Having added an extra prefix to the style rules this should prevent similar issues with the tabbed view.

**Comment by tonyzeoli** [comment]
Okay, good stuff. Sounds great. Thanks for staying with that one.
