### ISSUE TITLE
[Show Page] New Content Template Layout

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#72]
**Is your feature request related to a problem? Please describe.**
Let's revise the Show Page Layout per the attached wireframe.

**Describe the solution you'd like**
See the wireframe(s) PDFs attached with notes.
[radio-station show page layout.pdf](https://github.com/netmix/radio-station/files/3692765/radio-station.show.page.layout.pdf)
[radio-station layout posts.pdf](https://github.com/netmix/radio-station/files/3692801/radio-station.layout.posts.pdf)

**Describe alternatives you've considered**
N/A
**Additional context**
We're going to need media queries, as well.
For the row with the Show Details and Show Times, we'll want the thumbnail and audio button to load first in mobile, then the Show Details, then the Show Times.

The TABS should still be consistent in mobile, but maybe the font size is smaller. We'll probalby be adding a fourth tab: Archives, so we'll want to consider that for the future.

**Comment by tonyzeoli** [comment]
Tony, I rethought the Show page layout after meeting with the WPVM team today and doing some research. I think hiding the blog posts behind the last tab is not a great idea, because they are going to front the show archives or any content that the Show wants to feature. I was looking at some major radio station websites last night and came to the realization that I probably should move the show description into the three-column area and just have Posts and Playlists as tabs.

Please see the attached wireframe and let me know your thoughts.

[radio-station layout version 2.pdf](https://github.com/netmix/radio-station/files/3764054/radio-station.layout.version.2.pdf)

**Comment by tonyzeoli** [comment]
@majick777 Here's the mobile view wireframe, so you can see the stacking order of the content. I think this works out okay.

[radio-station layout mobile v1pdf.pdf](https://github.com/netmix/radio-station/files/3764495/radio-station.layout.mobile.v1pdf.pdf)

**Comment by tonyzeoli** [comment]
@majick777 Please review v 2.1 of the wireframe. In it, I have changed the layout of "Show Times" which is supposed to be named, "Schedule." (I got that wrong and just corrected it).

I have:

- added a designation for Eastern Standard Time with an accompanying time zone icon
- added a "repeat" icon for shows that "encore presentations" since the words won't fit with the new layout. I do not expect this to reflect in the master schedule just yet. Only the Show Page where the words "encore presentation" would appear next to the time in the list.
- You can see that I have stacked the Day, Start Time, End Time on top of each other to save on space in the section on desktop and mobile.

[Radio Station Wireframes V2.1.pdf](https://github.com/netmix/radio-station/files/3764925/Radio.Station.Wireframes.V2.1.pdf)

**Comment by majick777** [comment]
Some random thoughts and notes...
- Have the display and pagination working now for show posts and show playlists lists.
- I'm not sure how the stacked day / start / end time is going to work with Shows that have multiple shifts on the same day... though I like the idea the format may just be too restrictive.
- Social Media icons can wait (#78)
- Desktop vs. Mobile View, we don't want to be heaps different, responsiveness widths are the way to go. With media queries we can shift / float elements differently for smaller screens.
- We don't have the Host pictures in place yet (we can't rely on gravatars) and this probably won't be until we have Host profiles working (which is slated for Pro.
- I have added a plugin option for the user to select their Timezone for display, as the internal WordPress one may be set to just a GMT offset and this is not be enough in itself to not display the Timezone code (of course we fallback to displaying that if the actual Timezone is not set.) 
- We can't rely on there being so much horizontal width that three columns of content will always fit. Perhaps a theme has a sidebar... or even two sidebars. Squeezing the About section into a column is not going to work, I much prefer the About section being below the Show info, so it has full width of whatever space is available. Which is also why the Tabbed format maximizes the content space.

Overall I think we may be getting too ambitious with the formatting for a first draft, if we ever want to get this out there I feel we need to keep it simple to begin with (which v1 was), and then prioritize which sections to improve upon... If we can take a look at the difference between v1 and the latest... what are the priority elements that:
1. We need to have in place in this version?
2. We want  to have in place next version?
3. We want to have in place in first Pro version?

**Comment by tonyzeoli** [comment]
Thanks for this. I think for the Show times then, we should stack the days vertical on the left. We can get rid of Day, Start Time, End Time in favor of the below. I should have thought about this, so that's a great catch and let's pivot on it and do as follows:

Show Times:
Sun: 6-8 am, 10-11 am, 12-2 pm
Mon: 6-8 am, 10-11 am*, 12-2 pm
Tue: 6-8 am, 10-11 am, 12-2 pm
Wed: 6-8 am, 10-11 am, 12-2 pm
Thur: 6-8 am, 10-11 am, 12-2 pm*
Fri: 6-8 am*, 10-11 am, 12-2 pm
Sat: 6-8 am, 10-11 am, 12-2 pm

* denotes encore presentation.

The issue now is showing Encore Presentation for a specific time or times. I've added a star next to times that might be designated as encore. Not useful to add that icon graphic in the wireframe now, would be too intrusive if 5 shows were encore. So, let's just go with the *  

Per your comment about mobile responsive, yes, everything should always stack in mobile in the same order as desktop. If there is any difference in my wireframes, disregard and follow your path.

I would lead with the Featured Image, first.

Then left hand show logo and social links below it, and right side About (description)

Then Show Info below that section.

I think people should read about the show first, then see the Show info below. Same as in the mobile version I have a wireframe for here.

I agree that there are going to be 640 left / 320 right for many sites that have sidebars. So squeezing content into 640 across three columns may not be ideal.

As for what we really want to have in place for 2.3.0 is the new layout. I think improving on the layout is paramount, because those improvements carry over to page builders in terms of what loads in Post Description area of page builder. We must catch up with that or we'll be behind the times. I'm seeing so many things break in page builders and people with limited budgets will not be able to usefully use our plugin in a page builder. They are no all too common, so we have to deal with that.

Second, the layout as it currently is sucks. No featured image. A Page needs an avatar in the logo area - we could just call it "Show Avatar" instead of Show Logo. Needs to be like a Facebook page or a Twitter profile.

We're going to need to address all this for 2.3.0 I think.

**Comment by majick777** [comment]
For the draft coding I had followed the layout of v1 wireframe, which was (very) basically:
Show Image - Show Info (links and player) - Show Schedule (one shift per line)
(Tabs) About - Posts - Playlists
Tab Content Display

If we want to avoid three columns, but still meet the desired requirements of having both Show Info and About/Content up the top (because really they are equally important things, as some people will be looking for the quick Info and others for the Content) - I would suggest we go with all the Show info all vertically stacked (floated) on the left below the Show Avatar with the About (or other tab) content on the right, so that (because the left column is floated) it wraps below the left column if it's content ends up higher than the info... on smaller screens this might be like a 50-50% column split (down to ~150-150), but on larger screens more like 20-80% (up to ~200-800)

Something like this (excuse the lack of wireframing here, I am just about to head out somewhere, but wanted to get this down...)
`Show Avatar ---- | (Tabs) About - Posts - Playlists` 
`Show Avatar ---- | Tab Content --------------------`
`Show Avatar ---- | Tab Content --------------------`
`Show Player  ---- | Tab Content --------------------`
`Show Icons ----- | Tab Content ---------------------`
`Show Info  ------ | Tab Content ---------------------`
`Show Info  ------ | Tab Content ---------------------`
`Show Schedule - | Tab Content---------------------`
`Show Schedule - | Tab Content---------------------`
`Show Schedule - | Tab Content---------------------`
`Tab Content Continues, Wraps Below Left Column`
`Tab Content Continues, Wraps Below Left Column`

I think this might provide for the most flexibility given we don't know what info/content/links for the Show will/won't be provided, but still allows for it all being provided. 

Then for wider content areas (greater than 960px?), we can use javascript to detect the content width and split the first column into two (show info and show schedule into a middle column, which would be like ~200-250-400) but otherwise maintain this overall design pattern so the content wraps underneath to the left. (Note that we can't use media queries in this instance, as they rely on screen width and so cannot account for sidebar(s).) 

Let me know if anything there is unclear, I can do some wireframes up to show what I mean more visually soon. This approach I believe would come closest to the new wireframe, except that the Show Schedule would be below the Show Info not below the Content (again I don't think having anything below the Content is a good idea because the height of that Content is an unknown.) and for the Mobile view it would just be a two-column layout as described.

As for what is to be included in 2.3.0, yes definitely we aiming to get this in as a main feature, what I was meaning with those three questions was referring to the specifics of this layout. At the moment the social media icons and host avatar we can leave off for Pro as mentioned, but there might be other things so thought I'd ask. But it looks like with this approach we might have everything else with it sorted after all...

**Comment by tonyzeoli** [comment]
![Radio Station Wireframes V2 2](https://user-images.githubusercontent.com/4053819/68986649-6a497a80-07ef-11ea-96fe-0dafa1b702c0.jpg)
What about this layout?

**Comment by tonyzeoli** [comment]
disregaerd the social icons out to the right...I'm just saving them in the doc for later

**Comment by majick777** [comment]
I was gonna add this as a separate issue but is really only relevent here. Firstly I managed to get the Show Header and Show Avatar uploads working as does the standard Featured Image one. Believe it or not, through a code sample found on the `wp.media` WordPress Codex page (well there's a first time for everything!) So that's good now.

As regards Show Avatars and Featured Images problem. The solution I came up with is this... since an existing Show Avatar can be already set as the "Featured Image" on Show posts, and we want those to be separate things, when a Show is edited - or a Show Avatar is displayed via the plugin - the existing featured image ID (_thumbnail_id meta) is copied to the new Show Avatar post meta (show_avatar), and an extra (hidden) post meta switch is added indicating this has occurred. 

Why? First, this preserves existing Feature Image data that is set for Show Avatar... Now they both have the same value and so both plugin calls for the Show Avatar and Template calls to the thumbnail/featured image will work. This may mean (in some theme's templates) that the Featured Image) is shown above the Show post. But now it can be removed/replaced without affecting the Show Avatar display, or just removed and a (wide) Show Header Image used instead.

Further, a plugin option has been added so users can select whether to use a single post template (single.php) or a single page template (page.php) for the Show display (as they may be slightly different as we found.) This required some filtering of the template hierarchy for this post type. If the specified template is not found, both will fall back to singular.php and then index.php as is in the standard WordPress template hierarchy.

**Comment by tonyzeoli** [comment]
Okay, this is a level of complexity that seems, if I'm understanding correctly, provides a solution for moving a featured image that pre-exists to the Avatar feature, so that the Avatar does not fill the Featured Image section and look bad. Is that correct? I'd have to see it to understand it, so let me know if there's somewhere I can play with it - on the demo site or elsewhere. If not, no worries.

As for Posts verus Pages option, again, I'd have to see that and better understand the "why." The problems I'd found were in the data not displaying properly in site builders. Why someone would use the Posts template, I'm not sure of, so we'll chat about that. Seems like a good idea, but I guess I just need a little clarity on the why, as I'm not understanding it as good as I should from this explanation.

**Comment by tonyzeoli** [comment]
@majick777 Here's another layout I attempted tonight.

I thought that instead of printing out the schedule in text, we could use a grid to show the show times assigned to the show. That way, we don't have to worry so much about extending out to the right a long list of possible show times. The grid fills in with the assigned show times in a color in the grid. And, it doesn't print the entire hours from 12:00 am to 11:59 pm. It just shows you only the hours and fills in the days that the show airs. What are your thoughts on this?

![Radio Station Wireframes V3](https://user-images.githubusercontent.com/4053819/69001641-66316180-08b0-11ea-9b84-0947cce7a02b.jpg)

**Comment by majick777** [comment]
Decided to split that discussion out after all to save confusion.

**Comment by majick777** [comment]
So this is what a Draft 2 example of the layout according to what I was describing looks like...
![image](https://user-images.githubusercontent.com/6732852/69391351-acf6df80-0d26-11ea-8312-f62609d35e40.png)

- This is mostly an attempt to get the Show About content to the most topmost part of the page possible, but with having a fairly equal importance to the Show info. 
- Overall this layout does seem optimal to allow for varying window widths and resizing (note nothing special is in place for this yet but it handles width changes fairly gracefully without it.)
- Minimal styles are used here (mostly for positioning) so most things are left to the theme and user customization. Some block position changes are possible with user styles, for example, floating the three info blocks inline across the top or floating them right instead of left... These could perhaps be layout options?
- I feel it's important that having anything *under* the Show About content is not feasible as we don't know the length. Especially as we know existing users have already put long content in the About section over which we have no control. Having the Schedule or other Info pushed to the bottom on any page would mean it could go completely missing for a site visitor.
- Similarly we can't rely on the Featured Image or Show Header image being there, so incorporating that anywhere but above the rest of the layout doesn't seem feasible either.
- I'm not sure how the width-wise Schedule times table would work yet, if something is on in the morning and something at night it is going to turn out huge and we are trying to maximise on space... maybe a mouse hover box effect (like the proposed show meta hover box) would work for this one though?

**Comment by tonyzeoli** [comment]
Log into Skype


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  az@digitalstrategyworks.com
<az@digitalstrategyworks.com>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
<https://calendly.com/tonyzeoli> Schedule a 30-minute Meeting
<https://calendly.com/tonyzeoli>
<https://digitalstrategyworks.com/clearly-better-days-cbd-oil-ecommerce-site-enhancements/2019/10/07/2841/>
Latest
post: Clearly Better Days CBD Oil Ecommerce Site Enhancements
<https://digitalstrategyworks.com/clearly-better-days-cbd-oil-ecommerce-site-enhancements/2019/10/07/2841/>


<https://gsuite.google.com/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=https://goo.gl/BG4yH8>
<https://facebook.com/digitalstrategyworks>   <http://dswks>
<https://linkedin.com/in/+tonyzeoli>
<https://www.youtube.com/+digitalstrategyworks>

**Comment by tonyzeoli** [comment]
On Thu, Nov 21, 2019 at 9:06 PM majick777 <notifications@github.com> wrote:

> So this is what a Draft 2 example of the layout according to what I was
> describing looks like...
> [image: image]
> <https://user-images.githubusercontent.com/6732852/69391351-acf6df80-0d26-11ea-8312-f62609d35e40.png>
>
>    - This is mostly an attempt to get the Show About content to the most
>    topmost part of the page possible, but with having a fairly equal
>    importance to the Show info.
>
> I'm going to disagree here. Almost all radio station websites I've
checked, the Show Description is printed soley by itself without tabbed
browsing.

The issue is hiding Blog Posts behind a tab. Most radio station websites in
my research have Posts floating under the description. If they aren't
visible, no one will read them. No one is going to click on the tab for
blog posts, but they will for Episodes and Playlists. So, we need that
content front and center.





>
>    - Overall this layout does seem optimal to allow for varying window
>    widths and resizing (note nothing special is in place for this yet but it
>    handles width changes fairly gracefully without it.)
>
>
We are going to have more tabs in the future, like Episodes, so have the
show content on the top centers the user on what the show is about, then
the tabs below will get them to interact with the content that way. I just
don't see blog posts hidden being an optimal situation. Content is what
drives people around the merry go round of a site, so hiding recent posts
is not going to help when there is news about programming or special guests
and that sort of thing. Or, when there was a guest on that was popular and
the person wants to go to the show page blog and see the post about that
gues.



>
>    - Minimal styles are used here (mostly for positioning) so most things
>    are left to the theme and user customization. Some block position changes
>    are possible with user styles, for example, floating the three info blocks
>    inline across the top or floating them right instead of left... These could
>    perhaps be layout options?
>
> Possibly, but again, hiding the posts is going to be a problem.



>
>    - I feel it's important that having anything *under* the Show About
>    content is not feasible as we don't know the length. Especially as we know
>    existing users have already put long content in the About section over
>    which we have no control. Having the Schedule or other Info pushed to the
>    bottom on any page would mean it could go completely missing for a site
>    visitor.
>
> True, I had a meeting with WPVM today and they said they want their hosts
to use the system as intended. If it breaks for some people because they
didn't know, then that's a pain point, but that's why I have to educate
through the blog and newsletter what's coming and how to anticipate that
change. Also, we could limit the character count of the About section too,
to make sure that people don't max out. You don't need more than 5,000
characters to describe your show.




>
>    - Similarly we can't rely on the Featured Image or Show Header image
>    being there, so incorporating that anywhere but above the rest of the
>    layout doesn't seem feasible either.
>
> We can't, but we can preload an image that appears there and then they can
just change it. Or, we can set a prompt to upload a Featured Image.
Remember, with Facebook, it's emplty until you add an image. Same with
Twitter. We just put a background color there and say, "Add Image." if we
can.


>    - I'm not sure how the width-wise Schedule times table would work yet,
>    if something is on in the morning and something at night it is going to
>    turn out huge and we are trying to maximise on space... maybe a mouse hover
>    box effect (like the proposed show meta hover box) would work for this one
>    though?
>
> Yeah, I was trying to give an option for a visual view of the schedule for
a Show instead of just typing it out on the page.

Maybe we could just do something like:

------------------ M T W T F
2pm - 4pm      •
5 pm - 8 pm .        •

**Comment by majick777** [comment]
Sorry was out of time had to get on the road.

Ok yeah hmmm definitely didn't put the same kind of importance on Show Posts that you're talking about. 

We havr the same concern though, that all the content should be easily accessible. 

If we don't want the posts hidden behind a tab or lost at the end of a page, there's Still a few things we could do about this...

**Comment by majick777** [comment]
ack whoops phone fail. so yeah one option would be to put a "Latest Posts" or "Show News" (3?) mini-section above the show description and/or tabs. I think that could work rather well like an announcements/new ticker of sorts.

Another would be to give the user more layout options as mentioned, in this case of placing the tabs above or below show description... but also another option of having them not as tabs at all but each as (full-width) section blocks as you scroll down the page. 

We could limit the length of the show description as you say, but preferably not by word count but rather by height, with the full content available but scrollable within the limited height. 

So yeah we can chat about the pros and cons of different solutions here and work out which to go for when i get back. For now, back on the road for me...

**Comment by tonyzeoli** [comment]
Ok, thanks for considering the importance. We should definitely have verbal
discussion to finalize this decision point, so that we're both on the same
page and can agree on the best solution.

Let me know if you can chat your evening time on Monday.

**Comment by tonyzeoli** [comment]
@majick777 Here's a new wireframe. I did find this Sound Manager HTML5 player I thought might be super cool to add. Maybe a PRO feature? That the user can switch between a standard player and this player? They also have an experimental cassette and turntable player on the website here: 

http://www.schillmania.com/projects/soundmanager2/

We could add those in PRO version, which would be a cool feature.
[Radio Station Wireframes V2.4.pdf](https://github.com/netmix/radio-station/files/3935795/Radio.Station.Wireframes.V2.4.pdf)

**Comment by majick777** [comment]
Gonna call this one done too, as there hasn't been any further issues lately that I'm aware of.
