### ISSUE TITLE
Show Times reverting back to original selection on save action

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#98]
**Is your developer task related to a problem or a requirement? Please describe.**

When I went to change the Show Schedule for Show 3 to eliminate conflicts, I couldn't Save the changes. Not sure if this is because there are still conflicts.

**Describe the solution you'd like**

When I changed the show times to set them from 5 am to 7 am for Show 3, each time I saved, the start time reverted to 1 am.

**Describe alternatives you've considered**

No alternatives considered.

**Additional context**

Please test Show 3 and set showtimes to 5 am to 7 am and watch revert back to 1 am.

**Comment by majick777** [comment]
Cannot seem to reproduce. Times match up for me and save correctly, maybe it was due to #100 or another fix I already made in the meantime. Can you retest?

PS. Can we make sure to file bugs in the Bugfixes Project not the Enhancements one, and if they are for the beta/development version tag it with the development label I just added, this way we can distinguish from bugs in the already released version.

**Comment by majick777** [comment]
Same cause as #99. There was a bug in start_hour selection matching, causing the new value to not be selected on the next page even though it was saved. Have tested your examples and seems to be working now. Retest and close if you're satisfied.

**Comment by majick777** [comment]
@tonyzeoli Can you recheck and close if fixed.

**Comment by tonyzeoli** [comment]
Fixed.
